export const DEMO_PROPERTY_STRUGGLING = {
  property: {
    id: 'demo-struggling-001',
    address: '1847 Riverside Drive',
    street_address: '1847 Riverside Drive',
    city: 'Vancouver',
    state: 'WA',
    zip_code: '98661',
    property_type: 'Single-Family Home',
    year_built: 2010,
    square_footage: 1850,
    bedrooms: 3,
    bathrooms: 2,
    stories: 'Single-Story',
    foundation_type: 'Concrete Slab',
    garage_type: 'Attached 2-car',
    is_demo: true,
    demo_type: 'struggling',
    baseline_completion: 20,
    health_score: 62,
    last_inspection_date: null,
    total_maintenance_spent: 0,
    estimated_disasters_prevented: 0,
    certificationLevel: null,
    breakdown: { condition: 26, maintenance: 18, improvement: 18 },
    created_date: '2025-01-01T00:00:00Z'
  },
  
  systems: [
    {
      id: 'demo-s-sys-001',
      property_id: 'demo-struggling-001',
      system_type: 'HVAC System',
      nickname: 'Main HVAC',
      brand_model: 'Carrier 3-Ton Heat Pump',
      installation_year: 2007,
      condition: 'Fair',
      condition_notes: '18 years old (avg lifespan 15-20). No service records. Running but making noise.',
      warning_signs_present: ['Unusual noise', 'No maintenance history', 'Aging beyond typical lifespan'],
      last_service_date: null,
      next_service_date: null,
      estimated_lifespan_years: 15,
      replacement_cost_estimate: 6500,
      photo_urls: [],
      created_date: '2025-01-01T00:00:00Z'
    },
    {
      id: 'demo-s-sys-002',
      property_id: 'demo-struggling-001',
      system_type: 'Water & Sewer/Septic',
      nickname: 'Water Heater',
      brand_model: 'Rheem 40-Gal Gas',
      installation_year: 2009,
      condition: 'Fair',
      condition_notes: '16 years old (avg lifespan 10-15). Never been serviced. Still works but age is concerning.',
      warning_signs_present: ['Past typical lifespan', 'No maintenance history', 'Unknown condition'],
      last_service_date: null,
      next_service_date: null,
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 1200,
      photo_urls: [],
      created_date: '2025-01-01T00:00:00Z'
    },
    {
      id: 'demo-s-sys-003',
      property_id: 'demo-struggling-001',
      system_type: 'Roof System',
      nickname: 'Main Roof',
      brand_model: '3-Tab Asphalt Shingles',
      installation_year: 2010,
      condition: 'Fair',
      condition_notes: '15 years old. Some missing shingles. Gutters clogged. No recent inspection.',
      warning_signs_present: ['Missing shingles', 'Clogged gutters', 'No inspection history'],
      last_service_date: null,
      next_service_date: null,
      estimated_lifespan_years: 20,
      replacement_cost_estimate: 9000,
      photo_urls: [],
      created_date: '2025-01-01T00:00:00Z'
    },
    {
      id: 'demo-s-sys-004',
      property_id: 'demo-struggling-001',
      system_type: 'Electrical System',
      nickname: 'Main Panel',
      brand_model: '150A Main Panel',
      installation_year: 2010,
      condition: 'Poor',
      condition_notes: 'GFCI outlets near water NOT working. Some outlets not functioning. No recent inspection.',
      warning_signs_present: ['Failed GFCI outlets', 'Non-functional outlets', 'Safety hazard'],
      last_service_date: null,
      estimated_lifespan_years: 40,
      replacement_cost_estimate: 3500,
      photo_urls: [],
      created_date: '2025-01-01T00:00:00Z'
    },
    {
      id: 'demo-s-sys-005',
      property_id: 'demo-struggling-001',
      system_type: 'CO Detector',
      nickname: 'Carbon Monoxide Detectors',
      brand_model: 'None',
      installation_year: null,
      condition: 'Urgent',
      condition_notes: 'NO CARBON MONOXIDE DETECTORS INSTALLED. Critical safety issue.',
      warning_signs_present: ['No CO detectors', 'Life safety hazard'],
      last_service_date: null,
      estimated_lifespan_years: 7,
      replacement_cost_estimate: 100,
      photo_urls: [],
      created_date: '2025-01-01T00:00:00Z'
    },
    {
      id: 'demo-s-sys-006',
      property_id: 'demo-struggling-001',
      system_type: 'Smoke Detector',
      nickname: 'Smoke Detectors',
      brand_model: 'Battery-Powered (unknown age)',
      installation_year: null,
      condition: 'Poor',
      condition_notes: 'Unknown age. Batteries likely dead. Need replacement.',
      warning_signs_present: ['Unknown age', 'Unknown battery status', 'Safety concern'],
      last_service_date: null,
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 200,
      photo_urls: [],
      created_date: '2025-01-01T00:00:00Z'
    }
  ],

  tasks: [],

  inspections: [],

  maintenanceHistory: [],

  stats: {
    total_systems: 6,
    systems_good: 0,
    systems_flagged: 4,
    systems_urgent: 2,
    total_tasks: 0,
    tasks_urgent: 0,
    tasks_high: 0,
    tasks_medium: 0,
    tasks_low: 0,
    total_estimated_savings: 0,
    health_score: 62
  }
};