export const DEMO_PROPERTY_HOMEOWNER = {
  property: {
    id: 'demo-homeowner-001',
    address: '2847 Maple Grove Lane',
    street_address: '2847 Maple Grove Lane',
    city: 'Vancouver',
    state: 'WA',
    zip_code: '98661',
    property_type: 'Single-Family Home',
    year_built: 2015,
    square_footage: 2400,
    bedrooms: 4,
    bathrooms: 2.5,
    stories: 'Two-Story',
    foundation_type: 'Full Basement',
    garage_type: 'Attached 2-car',
    is_demo: true,
    demo_type: 'homeowner',
    baseline_completion: 100,
    health_score: 78,
    last_inspection_date: '2024-10-15',
    total_maintenance_spent: 3200,
    estimated_disasters_prevented: 7200,
    created_date: '2024-01-01T00:00:00Z'
  },
  
  systems: [
    {
      id: 'demo-h-sys-001',
      property_id: 'demo-homeowner-001',
      system_type: 'HVAC System',
      nickname: 'Main Heat Pump',
      brand_model: 'Lennox XC25 Heat Pump',
      installation_year: 2017,
      condition: 'Good',
      condition_notes: 'Serviced every 6 months. Last service: April 2024. Filter changed quarterly. Running at 95% efficiency.',
      last_service_date: '2024-04-10',
      next_service_date: '2024-10-15',
      estimated_lifespan_years: 15,
      replacement_cost_estimate: 8500,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-002',
      property_id: 'demo-homeowner-001',
      system_type: 'Water & Sewer/Septic',
      nickname: 'Water Heater',
      brand_model: 'Rheem ProTerra 50-Gal Hybrid',
      installation_year: 2016,
      condition: 'Fair',
      condition_notes: 'Showing signs of age. Minor sediment buildup detected during last flush. No leaks. Plan replacement within 12-18 months.',
      warning_signs_present: ['Sediment buildup', 'Age approaching end of lifespan'],
      last_service_date: '2024-03-15',
      next_service_date: '2025-03-15',
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 1800,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-003',
      property_id: 'demo-homeowner-001',
      system_type: 'Roof System',
      nickname: 'Main Roof',
      brand_model: 'CertainTeed Landmark AR Shingles',
      installation_year: 2015,
      condition: 'Good',
      condition_notes: '30-year architectural shingles. No missing/damaged shingles. Flashing intact. Gutters clean.',
      last_service_date: '2024-09-20',
      next_service_date: '2025-09-20',
      estimated_lifespan_years: 30,
      replacement_cost_estimate: 12000,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-004',
      property_id: 'demo-homeowner-001',
      system_type: 'Plumbing System',
      nickname: 'Main Plumbing',
      brand_model: 'Type L Copper Piping',
      installation_year: 2015,
      condition: 'Good',
      condition_notes: 'Copper supply lines, PVC drains. No visible leaks. Water pressure normal (60 PSI).',
      last_service_date: '2024-10-01',
      estimated_lifespan_years: 50,
      replacement_cost_estimate: 8000,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-005',
      property_id: 'demo-homeowner-001',
      system_type: 'Electrical System',
      nickname: 'Main Panel',
      brand_model: 'Square D 200A Main Panel',
      installation_year: 2015,
      condition: 'Excellent',
      condition_notes: '200-amp service. 32 circuit breakers. All labeled. GFCI outlets in kitchen, bathrooms, garage.',
      last_service_date: '2024-06-10',
      estimated_lifespan_years: 40,
      replacement_cost_estimate: 3500,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-006',
      property_id: 'demo-homeowner-001',
      system_type: 'Windows & Doors',
      nickname: 'All Windows',
      brand_model: 'Pella 250 Series Vinyl Double-Hung',
      installation_year: 2015,
      condition: 'Fair',
      condition_notes: 'Dual-pane vinyl windows. 3 windows have broken seals (foggy between panes). Consider replacement for those 3 within 1-2 years.',
      warning_signs_present: ['3 windows with failed seals', 'Reduced efficiency'],
      estimated_lifespan_years: 20,
      replacement_cost_estimate: 4500,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-007',
      property_id: 'demo-homeowner-001',
      system_type: 'Foundation & Structure',
      nickname: 'Foundation',
      brand_model: '8-inch Poured Concrete',
      installation_year: 2015,
      condition: 'Excellent',
      condition_notes: 'Poured concrete walls. No visible cracks. Proper drainage. Sump pump functioning.',
      last_service_date: '2024-09-01',
      estimated_lifespan_years: 100,
      replacement_cost_estimate: 50000,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-008',
      property_id: 'demo-homeowner-001',
      system_type: 'Basement/Crawlspace',
      nickname: 'Sump Pump',
      brand_model: 'Zoeller M53 Mighty-Mate',
      installation_year: 2015,
      condition: 'Good',
      condition_notes: '1/3 HP submersible pump with battery backup. Tested quarterly. At end of typical 10-year lifespan.',
      last_service_date: '2024-09-15',
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 800,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-009',
      property_id: 'demo-homeowner-001',
      system_type: 'Washing Machine',
      nickname: 'Washer Hoses',
      brand_model: 'Floodchek Braided Stainless Steel',
      installation_year: 2022,
      condition: 'Excellent',
      condition_notes: 'Braided stainless steel hoses (replaced rubber hoses). Auto-shutoff feature. No leaks.',
      last_service_date: '2024-06-01',
      estimated_lifespan_years: 5,
      replacement_cost_estimate: 50,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-010',
      property_id: 'demo-homeowner-001',
      system_type: 'Smoke Detector',
      nickname: 'All Smoke Detectors (6)',
      brand_model: 'First Alert Hardwired with Battery Backup',
      installation_year: 2015,
      condition: 'Urgent',
      condition_notes: 'Hardwired interconnected system. Units are 10 years old - REPLACE IMMEDIATELY per manufacturer guidelines.',
      warning_signs_present: ['Units at end of rated 10-year lifespan', 'Sensors may be degraded'],
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 300,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-011',
      property_id: 'demo-homeowner-001',
      system_type: 'Dishwasher',
      nickname: 'Kitchen Dishwasher',
      brand_model: 'Bosch SHPM65Z55N',
      installation_year: 2019,
      condition: 'Good',
      condition_notes: 'Stainless steel interior. Runs quietly. No leaks. Occasional error code (cleared by reset).',
      last_service_date: '2024-08-20',
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 800,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-012',
      property_id: 'demo-homeowner-001',
      system_type: 'Refrigerator',
      nickname: 'Kitchen Refrigerator',
      brand_model: 'Samsung RF28R7201SR French Door',
      installation_year: 2021,
      condition: 'Excellent',
      condition_notes: 'Counter-depth French door with ice maker. Cooling properly at optimal temps (37°F fridge, 0°F freezer).',
      last_service_date: '2024-07-01',
      estimated_lifespan_years: 13,
      replacement_cost_estimate: 2500,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-013',
      property_id: 'demo-homeowner-001',
      system_type: 'Range/Oven',
      nickname: 'Kitchen Range',
      brand_model: 'GE JGB735SPSS Gas Range',
      installation_year: 2015,
      condition: 'Good',
      condition_notes: '5-burner gas range. Oven calibrated correctly. All burners ignite properly.',
      last_service_date: '2024-06-15',
      estimated_lifespan_years: 15,
      replacement_cost_estimate: 1200,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-014',
      property_id: 'demo-homeowner-001',
      system_type: 'Microwave',
      nickname: 'Over-Range Microwave',
      brand_model: 'Whirlpool WMH53521HZ',
      installation_year: 2015,
      condition: 'Fair',
      condition_notes: 'Over-range microwave with vent. Heating inconsistent. Fan/light working. Consider replacement soon.',
      warning_signs_present: ['Magnetron may be weakening', 'Takes longer to heat'],
      estimated_lifespan_years: 9,
      replacement_cost_estimate: 400,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-015',
      property_id: 'demo-homeowner-001',
      system_type: 'Garage & Overhead Door',
      nickname: 'Garage Door Opener',
      brand_model: 'LiftMaster 8550W Elite Series',
      installation_year: 2020,
      condition: 'Good',
      condition_notes: 'Belt-drive opener with battery backup. WiFi enabled. Safety sensors functioning properly.',
      last_service_date: '2024-05-10',
      estimated_lifespan_years: 15,
      replacement_cost_estimate: 400,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-016',
      property_id: 'demo-homeowner-001',
      system_type: 'Exterior Siding & Envelope',
      nickname: 'Exterior Paint',
      brand_model: 'Sherwin-Williams Duration Exterior Acrylic',
      installation_year: 2018,
      condition: 'Fair',
      condition_notes: 'Beginning to fade and chalk. Minor peeling at eaves. Recommend repaint within 1-2 years to protect siding.',
      warning_signs_present: ['Paint oxidizing', 'Minor cracking at trim'],
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 5500,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    }
  ],
  
  tasks: [
    {
      id: 'demo-h-task-001',
      property_id: 'demo-homeowner-001',
      title: 'Replace All Smoke Detectors',
      description: 'All 6 smoke detectors are 10 years old and must be replaced per manufacturer specifications. This is a critical life-safety issue.',
      system_type: 'General',
      priority: 'High',
      cascade_risk_score: 10,
      cascade_risk_reason: 'CRITICAL - Failed detection could result in injury/death in fire',
      current_fix_cost: 300,
      delayed_fix_cost: 300,
      urgency_timeline: 'Immediate - Already at end of rated lifespan',
      diy_cost: 250,
      diy_difficulty: 'Medium',
      diy_time_hours: 2.5,
      contractor_cost: 350,
      status: 'Identified',
      source: 'INSPECTION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-002',
      property_id: 'demo-homeowner-001',
      title: 'Budget for Water Heater Replacement (2025)',
      description: 'Water heater is 9 years old with sediment buildup. Plan replacement in next 12-18 months before failure occurs.',
      system_type: 'Plumbing',
      priority: 'High',
      cascade_risk_score: 7,
      cascade_risk_reason: 'Failure could flood garage and damage stored items',
      current_fix_cost: 1800,
      delayed_fix_cost: 3500,
      cost_impact_reason: 'Emergency replacement costs 2x more + water damage cleanup',
      urgency_timeline: '12-18 months before failure likely',
      contractor_cost: 1800,
      status: 'Identified',
      source: 'INSPECTION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-003',
      property_id: 'demo-homeowner-001',
      title: 'Replace 3 Windows with Failed Seals',
      description: 'Living room and master bedroom windows have broken seals causing fogging. Reducing energy efficiency.',
      system_type: 'Windows/Doors',
      priority: 'Medium',
      cascade_risk_score: 4,
      cascade_risk_reason: 'Reduced efficiency, higher heating/cooling costs',
      current_fix_cost: 1200,
      delayed_fix_cost: 1200,
      urgency_timeline: '12-24 months',
      contractor_cost: 1200,
      status: 'Identified',
      source: 'INSPECTION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-004',
      property_id: 'demo-homeowner-001',
      title: 'Proactive Sump Pump Replacement',
      description: 'Sump pump is 10 years old (end of typical lifespan). Replace before next rainy season to avoid basement flooding.',
      system_type: 'Plumbing',
      priority: 'High',
      cascade_risk_score: 8,
      cascade_risk_reason: 'Failure during heavy rain could flood basement',
      current_fix_cost: 800,
      delayed_fix_cost: 5000,
      cost_impact_reason: 'Basement flood cleanup and damaged items',
      urgency_timeline: 'Before rainy season (Nov-Mar)',
      diy_cost: 600,
      diy_difficulty: 'Medium',
      diy_time_hours: 3.5,
      contractor_cost: 1000,
      status: 'Identified',
      source: 'PRESERVATION_RECOMMENDATION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-005',
      property_id: 'demo-homeowner-001',
      title: 'Fall Gutter Cleaning',
      description: 'Annual gutter cleaning before rainy season. Prevents water damage to roof and foundation.',
      system_type: 'Gutters',
      priority: 'Medium',
      cascade_risk_score: 6,
      cascade_risk_reason: 'Overflow can damage roof edge and foundation',
      current_fix_cost: 200,
      delayed_fix_cost: 3000,
      cost_impact_reason: 'Water damage to fascia boards and foundation issues',
      urgency_timeline: 'Within 2 weeks',
      diy_cost: 0,
      diy_difficulty: 'Easy',
      diy_time_hours: 2,
      contractor_cost: 200,
      status: 'Identified',
      source: 'SEASONAL_CHECKLIST',
      seasonal: true,
      recommended_completion_window: 'Before Nov 15',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-006',
      property_id: 'demo-homeowner-001',
      title: 'Replace Microwave',
      description: 'Microwave heating inconsistently. Magnetron likely failing. Replace within 6-12 months.',
      system_type: 'Appliances',
      priority: 'Low',
      cascade_risk_score: 2,
      current_fix_cost: 400,
      delayed_fix_cost: 400,
      urgency_timeline: '6-12 months',
      contractor_cost: 400,
      status: 'Identified',
      source: 'INSPECTION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-007',
      property_id: 'demo-homeowner-001',
      title: 'Schedule Exterior Repainting',
      description: 'Exterior paint fading and chalking. Repaint in 2025 to protect siding from water damage.',
      system_type: 'Exterior',
      priority: 'Medium',
      cascade_risk_score: 5,
      cascade_risk_reason: 'Delayed painting could allow water damage to siding',
      current_fix_cost: 5500,
      delayed_fix_cost: 12000,
      cost_impact_reason: 'Water damage could require siding replacement',
      urgency_timeline: 'Next summer (dry weather)',
      contractor_cost: 5500,
      status: 'Identified',
      source: 'INSPECTION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-008',
      property_id: 'demo-homeowner-001',
      title: 'Fall HVAC Service',
      description: 'Bi-annual HVAC service before heating season. Ensures system runs efficiently through winter.',
      system_type: 'HVAC',
      priority: 'Medium',
      current_fix_cost: 150,
      delayed_fix_cost: 150,
      contractor_cost: 150,
      status: 'Scheduled',
      scheduled_date: '2024-10-28',
      source: 'SEASONAL_CHECKLIST',
      seasonal: true,
      contractor_name: 'ABC Heating & Cooling',
      created_date: '2024-10-15T00:00:00Z'
    }
  ],

  inspections: [
    {
      id: 'demo-h-insp-001',
      property_id: 'demo-homeowner-001',
      inspection_type: 'Fall Winterization',
      season: 'Fall',
      inspection_date: '2024-10-15',
      completed_by: 'Self',
      status: 'Completed',
      items_checked: [
        { item: 'HVAC system serviced', status: 'Pass', notes: 'Serviced Oct 10' },
        { item: 'Gutters cleaned', status: 'Pass', notes: 'Cleaned Sept 20' },
        { item: 'Weather stripping inspected', status: 'Pass', notes: 'All intact' },
        { item: 'Outdoor faucets drained', status: 'Pass', notes: 'Completed Oct 15' },
        { item: 'Sump pump tested', status: 'Pass', notes: 'Working properly' },
        { item: 'Smoke detectors tested', status: 'Fail', notes: 'Need replacement (10 years old)' }
      ],
      findings: '5 of 6 items passed. Smoke detectors flagged for replacement.',
      next_inspection_due: '2025-04-15',
      notes: 'Property ready for winter. Smoke detector replacement scheduled for Nov 9.'
    },
    {
      id: 'demo-h-insp-002',
      property_id: 'demo-homeowner-001',
      inspection_type: 'Spring Opening',
      season: 'Spring',
      inspection_date: '2024-04-20',
      completed_by: 'Self',
      status: 'Completed',
      items_checked: [
        { item: 'HVAC system serviced', status: 'Pass', notes: 'Serviced April 10' },
        { item: 'Gutters cleaned', status: 'Pass', notes: 'Cleaned April 15' },
        { item: 'Roof inspection', status: 'Pass', notes: 'No winter damage' },
        { item: 'Outdoor faucets turned on', status: 'Pass', notes: 'All working' },
        { item: 'Windows cleaned', status: 'Pass', notes: 'Completed' },
        { item: 'Landscaping check', status: 'Pass', notes: 'Irrigation system tested' }
      ],
      findings: 'All items passed. No issues detected.',
      next_inspection_due: '2024-10-15',
      notes: 'Property in excellent condition for summer.'
    }
  ],

  maintenanceHistory: [
    {
      id: 'demo-h-hist-001',
      property_id: 'demo-homeowner-001',
      system_id: 'demo-h-sys-009',
      date: '2022-06-01',
      type: 'Replacement',
      title: 'Upgraded Washing Machine Hoses',
      description: 'Replaced rubber hoses with braided stainless steel auto-shutoff hoses',
      cost: 45,
      completed_by: 'DIY',
      time_spent_hours: 0.5,
      notes: 'Easy upgrade. Prevents potential $5,000+ flood damage.',
      before_photo_url: null,
      after_photo_url: null,
      prevented_cost: 5000
    },
    {
      id: 'demo-h-hist-002',
      property_id: 'demo-homeowner-001',
      system_id: 'demo-h-sys-001',
      date: '2024-04-10',
      type: 'Service',
      title: 'Spring HVAC Service',
      description: 'Professional bi-annual HVAC maintenance',
      cost: 165,
      completed_by: 'ABC Heating & Cooling',
      time_spent_hours: 1.5,
      notes: 'Cleaned coils, changed filter, checked refrigerant. System running at 95% efficiency.',
      prevented_cost: 800
    },
    {
      id: 'demo-h-hist-003',
      property_id: 'demo-homeowner-001',
      system_id: 'demo-h-sys-003',
      date: '2024-04-20',
      type: 'Maintenance',
      title: 'Spring Gutter Cleaning',
      description: 'Removed debris and flushed downspouts',
      cost: 0,
      completed_by: 'DIY',
      time_spent_hours: 2,
      notes: 'Prevents foundation damage and basement flooding.',
      prevented_cost: 3000
    },
    {
      id: 'demo-h-hist-004',
      property_id: 'demo-homeowner-001',
      system_id: 'demo-h-sys-002',
      date: '2024-03-15',
      type: 'Service',
      title: 'Water Heater Flush',
      description: 'Annual sediment flush and anode rod inspection',
      cost: 150,
      completed_by: 'Plumbing Pro',
      time_spent_hours: 1,
      notes: 'Moderate sediment buildup. Anode rod 40% depleted. Plan replacement 2025.',
      prevented_cost: 1200
    },
    {
      id: 'demo-h-hist-005',
      property_id: 'demo-homeowner-001',
      system_id: 'demo-h-sys-008',
      date: '2024-09-15',
      type: 'Test',
      title: 'Sump Pump Quarterly Test',
      description: 'Tested sump pump operation and battery backup',
      cost: 0,
      completed_by: 'DIY',
      time_spent_hours: 0.25,
      notes: 'Pump working properly. Battery backup functional. Replace proactively before winter.',
      prevented_cost: 8000
    }
  ],

  preserveSchedules: [
    {
      id: 'demo-h-pres-001',
      season: 'Fall',
      title: 'Fall Winterization Checklist',
      month: 'October',
      tasks: [
        { 
          task: 'Schedule HVAC fall service', 
          frequency: 'Annual',
          importance: 'High',
          estimated_time: '1 hour (professional)',
          estimated_cost: 150,
          why_it_matters: 'Ensures heating system runs efficiently through winter. Prevents mid-winter breakdowns.',
          completed: true
        },
        { 
          task: 'Clean gutters and downspouts', 
          frequency: 'Bi-annual',
          importance: 'High',
          estimated_time: '2-3 hours',
          estimated_cost: 0,
          why_it_matters: 'Prevents water damage to foundation, basement flooding, and roof damage.',
          completed: true
        },
        { 
          task: 'Test sump pump', 
          frequency: 'Quarterly',
          importance: 'High',
          estimated_time: '15 minutes',
          estimated_cost: 0,
          why_it_matters: 'Pacific NW rainy season. Pump failure = $5K-$10K basement flood.',
          completed: true
        },
        { 
          task: 'Drain outdoor faucets', 
          frequency: 'Annual',
          importance: 'Medium',
          estimated_time: '30 minutes',
          estimated_cost: 0,
          why_it_matters: 'Prevents frozen pipes. Burst pipe = $1K-$3K repair.',
          completed: true
        },
        { 
          task: 'Check weather stripping', 
          frequency: 'Annual',
          importance: 'Medium',
          estimated_time: '1 hour',
          estimated_cost: 50,
          why_it_matters: 'Reduces heating costs by 10-15%. Saves $200-$300/year.',
          completed: true
        },
        { 
          task: 'Reverse ceiling fan direction', 
          frequency: 'Bi-annual',
          importance: 'Low',
          estimated_time: '10 minutes',
          estimated_cost: 0,
          why_it_matters: 'Pushes warm air down. Improves heating efficiency.',
          completed: false
        },
        { 
          task: 'Test smoke and CO detectors', 
          frequency: 'Monthly',
          importance: 'Critical',
          estimated_time: '5 minutes',
          estimated_cost: 0,
          why_it_matters: 'Life safety. Replace units every 10 years.',
          completed: true,
          urgent_note: 'UNITS ARE 10 YEARS OLD - REPLACE IMMEDIATELY'
        }
      ],
      completion_percentage: 86,
      status: 'In Progress',
      notes: 'Most tasks complete. Smoke detector replacement scheduled for Nov 9.'
    },
    {
      id: 'demo-h-pres-002',
      season: 'Spring',
      title: 'Spring Home Opening Checklist',
      month: 'April',
      tasks: [
        { 
          task: 'Schedule HVAC spring service', 
          frequency: 'Annual',
          importance: 'High',
          estimated_time: '1 hour (professional)',
          estimated_cost: 150,
          completed: true
        },
        { 
          task: 'Clean gutters and downspouts', 
          frequency: 'Bi-annual',
          importance: 'High',
          estimated_time: '2-3 hours',
          estimated_cost: 0,
          completed: true
        },
        { 
          task: 'Test sump pump', 
          frequency: 'Quarterly',
          importance: 'High',
          estimated_time: '15 minutes',
          estimated_cost: 0,
          completed: true
        },
        { 
          task: 'Turn on outdoor faucets', 
          frequency: 'Annual',
          importance: 'Medium',
          estimated_time: '15 minutes',
          estimated_cost: 0,
          completed: true
        },
        { 
          task: 'Inspect roof for winter damage', 
          frequency: 'Annual',
          importance: 'High',
          estimated_time: '30 minutes',
          estimated_cost: 0,
          completed: true
        },
        { 
          task: 'Power wash exterior', 
          frequency: 'Annual',
          importance: 'Medium',
          estimated_time: '3-4 hours',
          estimated_cost: 200,
          completed: false
        },
        { 
          task: 'Service lawn equipment', 
          frequency: 'Annual',
          importance: 'Low',
          estimated_time: '1 hour',
          estimated_cost: 75,
          completed: true
        }
      ],
      completion_percentage: 100,
      status: 'Completed',
      completed_date: '2024-04-25',
      notes: 'All spring tasks completed successfully.'
    }
  ],

  upgrades: [
    {
      id: 'demo-h-upg-001',
      property_id: 'demo-homeowner-001',
      title: 'Attic Insulation Upgrade',
      category: 'Energy Efficiency',
      description: 'Add blown-in insulation to increase R-value from R-30 to R-49',
      priority: 'High',
      status: 'Planned',
      target_date: '2025-06-01',
      estimated_cost_low: 1500,
      estimated_cost_high: 2500,
      estimated_roi_years: 5,
      annual_savings: 400,
      total_savings_10yr: 4000,
      payback_period_years: 5,
      rebates_available: [
        { source: 'Energy Trust of Oregon', amount: 200, details: 'Insulation rebate' }
      ],
      why_worth_it: 'Reduces heating/cooling costs by 15-20%. Improves comfort. Increases home value.',
      notes: 'Get quotes in spring. Complete before summer heat.',
      research_links: []
    },
    {
      id: 'demo-h-upg-002',
      property_id: 'demo-homeowner-001',
      title: 'Smart Thermostat Installation',
      category: 'Smart Home',
      description: 'Replace manual thermostat with Ecobee Smart Thermostat Premium',
      priority: 'Medium',
      status: 'Researching',
      target_date: '2025-03-01',
      estimated_cost_low: 200,
      estimated_cost_high: 300,
      estimated_roi_years: 2,
      annual_savings: 150,
      total_savings_10yr: 1500,
      payback_period_years: 1.7,
      rebates_available: [
        { source: 'Local Utility', amount: 50, details: 'Smart thermostat rebate' }
      ],
      why_worth_it: 'Save 23% on heating/cooling. Remote control. Auto-scheduling. Easy DIY install.',
      notes: 'Wait for Black Friday sale. Check utility rebates.',
      research_links: []
    },
    {
      id: 'demo-h-upg-003',
      property_id: 'demo-homeowner-001',
      title: 'LED Light Bulb Conversion',
      category: 'Energy Efficiency',
      description: 'Replace all incandescent and CFL bulbs with LED',
      priority: 'Low',
      status: 'In Progress',
      target_date: '2024-12-31',
      estimated_cost_low: 150,
      estimated_cost_high: 200,
      estimated_roi_years: 1,
      annual_savings: 180,
      total_savings_10yr: 1800,
      payback_period_years: 1,
      rebates_available: [],
      why_worth_it: 'Last 25x longer. Use 75% less energy. Better light quality.',
      notes: '60% complete. Replace as bulbs burn out.',
      progress_percentage: 60
    }
  ],

  portfolioMetrics: {
    total_properties: 1,
    total_units: 1,
    total_property_value: 550000,
    total_equity: 250000,
    total_monthly_income: 0,
    average_health_score: 78,
    properties_needing_attention: 1,
    upcoming_capex_12mo: 2000,
    maintenance_cost_per_unit: 1200,
    total_maintenance_invested: 4800,
    total_savings_from_prevention: 7200,
    roi_on_maintenance: 150,
    message: 'Scale feature designed for investors with 2+ properties. Add more properties to unlock portfolio analytics.'
  },
  
  stats: {
    total_systems: 16,
    systems_good: 9,
    systems_flagged: 6,
    systems_urgent: 1,
    total_tasks: 8,
    tasks_urgent: 1,
    tasks_high: 3,
    tasks_medium: 3,
    tasks_low: 1,
    total_estimated_savings: 7200,
    health_score: 78
  }
};