// Investor Demo Data - 3-Property Portfolio
import { getDemoDate, getDemoPastDate, getDemoFutureDate } from './demoDates';

export const DEMO_PORTFOLIO_INVESTOR = {
  portfolioStats: {
    totalProperties: 3,
    totalUnits: 7,
    totalValue: 785000,
    totalEquity: 412000,
    totalDebt: 373000,
    ltv: 47.5,
    averageHealthScore: 81,
    occupancyRate: 86,
    monthlyRevenue: 4850,
    monthlyExpenses: 2140,
    netCashFlow: 2710,
    portfolioROI: 18.2,
    cashOnCashReturn: 22.4,
    preventedCosts: 18400,
    yearToDateMaintenance: 8950
  },

  properties: [
    {
      id: 'demo-investor-1',
      nickname: 'Maple Street Duplex',
      address: '1247 Maple Street',
      city: 'Vancouver',
      state: 'WA',
      zip_code: '98661',
      property_type: 'Duplex',
      door_count: 2,
      year_built: 1998,
      square_footage: 2400,
      bedrooms: 4,
      bathrooms: 2,
      purchase_date: '2019-03',
      purchase_price: 285000,
      current_value: 340000,
      mortgage_balance: 198000,
      equity: 142000,
      monthly_rent: 2400,
      monthly_mortgage: 1180,
      health_score: 84,
      last_inspection_date: '2024-10-15',
      occupancy_status: 'Both units occupied',
      baseline_completion: 100,
      units: [
        {
          unit_id: 'A',
          nickname: 'Unit A',
          bedrooms: 2,
          bathrooms: 1,
          square_footage: 1200,
          occupancy_status: 'Tenant-Occupied',
          tenant_name: 'Johnson Family',
          monthly_rent: 1200
        },
        {
          unit_id: 'B',
          nickname: 'Unit B',
          bedrooms: 2,
          bathrooms: 1,
          square_footage: 1200,
          occupancy_status: 'Tenant-Occupied',
          tenant_name: 'Martinez Couple',
          monthly_rent: 1200
        }
      ]
    },
    {
      id: 'demo-investor-2',
      nickname: 'Oak Ridge Single Family',
      address: '3842 Oak Ridge Drive',
      city: 'Portland',
      state: 'OR',
      zip_code: '97202',
      property_type: 'Single-Family Home',
      door_count: 1,
      year_built: 2005,
      square_footage: 1850,
      bedrooms: 3,
      bathrooms: 2,
      purchase_date: '2021-07',
      purchase_price: 325000,
      current_value: 375000,
      mortgage_balance: 265000,
      equity: 110000,
      monthly_rent: 2250,
      monthly_mortgage: 1420,
      health_score: 88,
      last_inspection_date: '2024-09-28',
      occupancy_status: 'Tenant Occupied',
      baseline_completion: 100
    },
    {
      id: 'demo-investor-3',
      nickname: 'Cedar Court 4-Plex',
      address: '891 Cedar Court',
      city: 'Vancouver',
      state: 'WA',
      zip_code: '98664',
      property_type: 'Fourplex',
      door_count: 4,
      year_built: 1985,
      square_footage: 3600,
      bedrooms: 4,
      bathrooms: 4,
      purchase_date: '2023-01',
      purchase_price: 450000,
      current_value: 495000,
      mortgage_balance: 380000,
      equity: 115000,
      monthly_rent: 3600,
      monthly_mortgage: 2050,
      health_score: 72,
      last_inspection_date: '2024-11-01',
      occupancy_status: '3 occupied, 1 vacant',
      baseline_completion: 100,
      units: [
        { unit_id: '1A', nickname: 'Unit 1A', bedrooms: 1, bathrooms: 1, square_footage: 900, occupancy_status: 'Tenant-Occupied', monthly_rent: 900 },
        { unit_id: '2C', nickname: 'Unit 2C', bedrooms: 1, bathrooms: 1, square_footage: 900, occupancy_status: 'Tenant-Occupied', monthly_rent: 900 },
        { unit_id: '3B', nickname: 'Unit 3B', bedrooms: 1, bathrooms: 1, square_footage: 900, occupancy_status: 'Tenant-Occupied', monthly_rent: 900 },
        { unit_id: '4D', nickname: 'Unit 4D', bedrooms: 1, bathrooms: 1, square_footage: 900, occupancy_status: 'Vacant', monthly_rent: 0 }
      ]
    }
  ],

  systems: [
    // ==========================================
    // PROPERTY 1: MAPLE STREET DUPLEX (1998) - 16 SYSTEMS
    // ==========================================
    { id: 'sys-1', property_id: 'demo-investor-1', system_type: 'HVAC System', nickname: 'Unit A Furnace', brand_model: 'Carrier 80% Gas Furnace', installation_year: 2010, condition: 'Good', last_service_date: '2024-09-15', estimated_lifespan_years: 18, replacement_cost_estimate: 3500 },
    { id: 'sys-2', property_id: 'demo-investor-1', system_type: 'HVAC System', nickname: 'Unit B Furnace', brand_model: 'Carrier 80% Gas Furnace', installation_year: 2010, condition: 'Good', last_service_date: '2024-09-15', estimated_lifespan_years: 18, replacement_cost_estimate: 3500 },
    { id: 'sys-3', property_id: 'demo-investor-1', system_type: 'Roof System', nickname: 'Main Roof', brand_model: 'Asphalt Shingles', installation_year: 2014, condition: 'Good', estimated_lifespan_years: 20, replacement_cost_estimate: 8500 },
    { id: 'sys-4', property_id: 'demo-investor-1', system_type: 'Water & Sewer/Septic', nickname: 'Main Water Line', brand_model: 'Copper Supply', installation_year: 1998, condition: 'Good', estimated_lifespan_years: 50, replacement_cost_estimate: 4000 },
    { id: 'sys-5', property_id: 'demo-investor-1', system_type: 'Plumbing System', nickname: 'Unit A Water Heater', brand_model: 'Rheem 40-Gal Gas', installation_year: 2013, condition: 'Fair', estimated_lifespan_years: 10, replacement_cost_estimate: 1200 },
    { id: 'sys-6', property_id: 'demo-investor-1', system_type: 'Plumbing System', nickname: 'Unit B Water Heater', brand_model: 'Rheem 40-Gal Gas', installation_year: 2013, condition: 'Fair', estimated_lifespan_years: 10, replacement_cost_estimate: 1200 },
    { id: 'sys-7', property_id: 'demo-investor-1', system_type: 'Electrical System', nickname: 'Main Panel', brand_model: '200A Panel', installation_year: 1998, condition: 'Good', estimated_lifespan_years: 40, replacement_cost_estimate: 3000 },
    { id: 'sys-8', property_id: 'demo-investor-1', system_type: 'Foundation & Structure', nickname: 'Foundation', installation_year: 1998, condition: 'Good', estimated_lifespan_years: 100, replacement_cost_estimate: 40000 },
    { id: 'sys-9', property_id: 'demo-investor-1', system_type: 'Gutters & Downspouts', nickname: 'Gutters', installation_year: 1998, condition: 'Good', estimated_lifespan_years: 20, replacement_cost_estimate: 1500 },
    { id: 'sys-10', property_id: 'demo-investor-1', system_type: 'Windows & Doors', nickname: 'All Windows', installation_year: 1998, condition: 'Fair', estimated_lifespan_years: 25, replacement_cost_estimate: 6000 },
    { id: 'sys-11', property_id: 'demo-investor-1', system_type: 'Exterior Siding & Envelope', nickname: 'Siding', installation_year: 1998, condition: 'Good', estimated_lifespan_years: 30, replacement_cost_estimate: 12000 },
    { id: 'sys-12', property_id: 'demo-investor-1', system_type: 'Garage & Overhead Door', nickname: 'Garage Door', installation_year: 2008, condition: 'Good', estimated_lifespan_years: 20, replacement_cost_estimate: 1200 },
    { id: 'sys-13', property_id: 'demo-investor-1', system_type: 'Refrigerator', nickname: 'Unit A Fridge', installation_year: 2015, condition: 'Good', estimated_lifespan_years: 13, replacement_cost_estimate: 1200 },
    { id: 'sys-14', property_id: 'demo-investor-1', system_type: 'Refrigerator', nickname: 'Unit B Fridge', installation_year: 2016, condition: 'Good', estimated_lifespan_years: 13, replacement_cost_estimate: 1200 },
    { id: 'sys-15', property_id: 'demo-investor-1', system_type: 'Dishwasher', nickname: 'Unit A Dishwasher', installation_year: 2018, condition: 'Good', estimated_lifespan_years: 10, replacement_cost_estimate: 700 },
    { id: 'sys-16', property_id: 'demo-investor-1', system_type: 'Dishwasher', nickname: 'Unit B Dishwasher', installation_year: 2018, condition: 'Good', estimated_lifespan_years: 10, replacement_cost_estimate: 700 },
    
    // ==========================================
    // PROPERTY 2: OAK RIDGE SINGLE FAMILY (2005) - 16 SYSTEMS
    // ==========================================
    { id: 'sys-17', property_id: 'demo-investor-2', system_type: 'HVAC System', nickname: 'Main System', brand_model: 'Trane XV20i Heat Pump', installation_year: 2005, condition: 'Excellent', last_service_date: '2024-09-15', estimated_lifespan_years: 20, replacement_cost_estimate: 6200 },
    { id: 'sys-18', property_id: 'demo-investor-2', system_type: 'Roof System', nickname: 'Composition Shingle', brand_model: 'GAF Timberline HD', installation_year: 2005, condition: 'Good', estimated_lifespan_years: 25, replacement_cost_estimate: 9500 },
    { id: 'sys-19', property_id: 'demo-investor-2', system_type: 'Water & Sewer/Septic', nickname: 'Main Plumbing', installation_year: 2005, condition: 'Excellent', estimated_lifespan_years: 50, replacement_cost_estimate: 5000 },
    { id: 'sys-20', property_id: 'demo-investor-2', system_type: 'Plumbing System', nickname: 'Water Heater', brand_model: 'AO Smith 50-Gal', installation_year: 2016, condition: 'Good', estimated_lifespan_years: 10, replacement_cost_estimate: 1400 },
    { id: 'sys-21', property_id: 'demo-investor-2', system_type: 'Electrical System', nickname: 'Main Panel', installation_year: 2005, condition: 'Excellent', estimated_lifespan_years: 40, replacement_cost_estimate: 3500 },
    { id: 'sys-22', property_id: 'demo-investor-2', system_type: 'Foundation & Structure', nickname: 'Foundation', installation_year: 2005, condition: 'Excellent', estimated_lifespan_years: 100, replacement_cost_estimate: 45000 },
    { id: 'sys-23', property_id: 'demo-investor-2', system_type: 'Windows & Doors', nickname: 'All Windows', installation_year: 2005, condition: 'Good', estimated_lifespan_years: 25, replacement_cost_estimate: 5500 },
    { id: 'sys-24', property_id: 'demo-investor-2', system_type: 'Exterior Siding & Envelope', nickname: 'Fiber Cement Siding', installation_year: 2005, condition: 'Excellent', estimated_lifespan_years: 50, replacement_cost_estimate: 15000 },
    { id: 'sys-25', property_id: 'demo-investor-2', system_type: 'Gutters & Downspouts', nickname: 'Gutters', installation_year: 2005, condition: 'Good', estimated_lifespan_years: 20, replacement_cost_estimate: 1600 },
    { id: 'sys-26', property_id: 'demo-investor-2', system_type: 'Garage & Overhead Door', nickname: 'Garage Door', installation_year: 2005, condition: 'Good', estimated_lifespan_years: 20, replacement_cost_estimate: 1400 },
    { id: 'sys-27', property_id: 'demo-investor-2', system_type: 'Refrigerator', nickname: 'Kitchen Fridge', installation_year: 2019, condition: 'Excellent', estimated_lifespan_years: 13, replacement_cost_estimate: 2000 },
    { id: 'sys-28', property_id: 'demo-investor-2', system_type: 'Dishwasher', nickname: 'Kitchen Dishwasher', installation_year: 2020, condition: 'Excellent', estimated_lifespan_years: 10, replacement_cost_estimate: 900 },
    { id: 'sys-29', property_id: 'demo-investor-2', system_type: 'Range/Oven', nickname: 'Kitchen Range', installation_year: 2005, condition: 'Good', estimated_lifespan_years: 15, replacement_cost_estimate: 1300 },
    { id: 'sys-30', property_id: 'demo-investor-2', system_type: 'Washing Machine', nickname: 'Washer', installation_year: 2018, condition: 'Good', estimated_lifespan_years: 11, replacement_cost_estimate: 800 },
    { id: 'sys-31', property_id: 'demo-investor-2', system_type: 'Dryer', nickname: 'Dryer', installation_year: 2018, condition: 'Good', estimated_lifespan_years: 13, replacement_cost_estimate: 700 },
    { id: 'sys-32', property_id: 'demo-investor-2', system_type: 'Smoke Detector', nickname: 'Smoke Detectors (5)', installation_year: 2020, condition: 'Good', estimated_lifespan_years: 10, replacement_cost_estimate: 200 },
    
    // ==========================================
    // PROPERTY 3: CEDAR COURT 4-PLEX (1985) - 16 SYSTEMS
    // ==========================================
    { id: 'sys-33', property_id: 'demo-investor-3', system_type: 'HVAC System', nickname: 'Building HVAC', brand_model: 'Carrier Gas Furnace', installation_year: 1985, condition: 'Fair', estimated_lifespan_years: 20, replacement_cost_estimate: 18000, warning_signs_present: ['Age - 39 years old', 'Higher utility bills'] },
    { id: 'sys-34', property_id: 'demo-investor-3', system_type: 'Roof System', nickname: 'Main Roof', brand_model: 'Asphalt Shingles', installation_year: 2003, condition: 'Fair', estimated_lifespan_years: 20, replacement_cost_estimate: 14500, warning_signs_present: ['Minor leaks in Unit 2C', 'Age - 22 years'] },
    { id: 'sys-35', property_id: 'demo-investor-3', system_type: 'Water & Sewer/Septic', nickname: 'Main Water Line', installation_year: 1985, condition: 'Fair', estimated_lifespan_years: 50, replacement_cost_estimate: 6000 },
    { id: 'sys-36', property_id: 'demo-investor-3', system_type: 'Plumbing System', nickname: 'Building Plumbing', installation_year: 1985, condition: 'Fair', estimated_lifespan_years: 50, replacement_cost_estimate: 12000 },
    { id: 'sys-37', property_id: 'demo-investor-3', system_type: 'Electrical System', nickname: 'Main Panel', installation_year: 1985, condition: 'Fair', estimated_lifespan_years: 40, replacement_cost_estimate: 4500 },
    { id: 'sys-38', property_id: 'demo-investor-3', system_type: 'Foundation & Structure', nickname: 'Foundation', installation_year: 1985, condition: 'Good', estimated_lifespan_years: 100, replacement_cost_estimate: 50000 },
    { id: 'sys-39', property_id: 'demo-investor-3', system_type: 'Windows & Doors', nickname: 'Building Windows', installation_year: 1998, condition: 'Fair', estimated_lifespan_years: 25, replacement_cost_estimate: 9800, warning_signs_present: ['Single-pane in some units'] },
    { id: 'sys-40', property_id: 'demo-investor-3', system_type: 'Exterior Siding & Envelope', nickname: 'Vinyl Siding', installation_year: 1995, condition: 'Fair', estimated_lifespan_years: 40, replacement_cost_estimate: 16000 },
    { id: 'sys-41', property_id: 'demo-investor-3', system_type: 'Gutters & Downspouts', nickname: 'Gutters', installation_year: 1985, condition: 'Fair', estimated_lifespan_years: 20, replacement_cost_estimate: 2200 },
    { id: 'sys-42', property_id: 'demo-investor-3', system_type: 'Garage & Overhead Door', nickname: 'Garage Door', installation_year: 2010, condition: 'Good', estimated_lifespan_years: 20, replacement_cost_estimate: 1500 },
    { id: 'sys-43', property_id: 'demo-investor-3', system_type: 'Refrigerator', nickname: 'Unit 1A Fridge', installation_year: 2016, condition: 'Good', estimated_lifespan_years: 13, replacement_cost_estimate: 1000 },
    { id: 'sys-44', property_id: 'demo-investor-3', system_type: 'Refrigerator', nickname: 'Unit 2C Fridge', installation_year: 2018, condition: 'Good', estimated_lifespan_years: 13, replacement_cost_estimate: 1000 },
    { id: 'sys-45', property_id: 'demo-investor-3', system_type: 'Refrigerator', nickname: 'Unit 3B Fridge', installation_year: 2015, condition: 'Fair', estimated_lifespan_years: 13, replacement_cost_estimate: 1000, warning_signs_present: ['Compressor noise'] },
    { id: 'sys-46', property_id: 'demo-investor-3', system_type: 'Driveways & Hardscaping', nickname: 'Parking Lot', installation_year: 2005, condition: 'Fair', estimated_lifespan_years: 20, replacement_cost_estimate: 8500 },
    { id: 'sys-47', property_id: 'demo-investor-3', system_type: 'Landscaping & Grading', nickname: 'Drainage System', installation_year: 1985, condition: 'Fair', estimated_lifespan_years: 30, replacement_cost_estimate: 4000 },
    { id: 'sys-48', property_id: 'demo-investor-3', system_type: 'Smoke Detector', nickname: 'Smoke Detectors (12)', installation_year: 2015, condition: 'Good', estimated_lifespan_years: 10, replacement_cost_estimate: 400 }
  ],

  tasks: [
    // ==========================================
    // TASKS FOR TODAY - FOR EXECUTE PAGE
    // ==========================================
    
    // PROPERTY 1: MAPLE STREET - TODAY
    {
      id: 'exec-today-1',
      property_id: 'demo-investor-1',
      title: 'Check thermostat settings - Both Units',
      description: 'Verify heating mode is set correctly for winter season.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 1,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-2',
      property_id: 'demo-investor-1',
      title: 'Test all smoke detectors - Unit A',
      description: 'Monthly smoke/CO detector testing.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-3',
      property_id: 'demo-investor-1',
      title: 'Test all smoke detectors - Unit B',
      description: 'Monthly smoke/CO detector testing.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-4',
      property_id: 'demo-investor-1',
      title: 'Inspect weather stripping - Unit A',
      description: 'Check door weather stripping before cold snap.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 1,
      system_type: 'Windows/Doors',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    {
      id: 'exec-today-5',
      property_id: 'demo-investor-1',
      title: 'Check for drafts - Unit B',
      description: 'Inspect windows and doors for cold air leaks.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 1,
      system_type: 'Windows/Doors',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    
    // PROPERTY 2: OAK RIDGE - TODAY
    {
      id: 'exec-today-6',
      property_id: 'demo-investor-2',
      title: 'Test all smoke/CO detectors',
      description: 'Monthly safety check.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    {
      id: 'exec-today-7',
      property_id: 'demo-investor-2',
      title: 'Inspect basement for moisture',
      description: 'Check for any water intrusion or dampness.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 3,
      system_type: 'Foundation',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    {
      id: 'exec-today-8',
      property_id: 'demo-investor-2',
      title: 'Check furnace operation',
      description: 'Verify furnace is running efficiently.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-9',
      property_id: 'demo-investor-2',
      title: 'Exterior walkthrough - storm prep',
      description: 'Check for loose items before winter storms.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'Exterior',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    
    // PROPERTY 3: CEDAR COURT - TODAY
    {
      id: 'exec-today-10',
      property_id: 'demo-investor-3',
      title: 'Common area inspection - Cedar Court',
      description: 'Check hallways, stairwells, exterior lighting.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    {
      id: 'exec-today-11',
      property_id: 'demo-investor-3',
      title: 'Smoke detector test - Unit 1A',
      description: 'Monthly safety check.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      unit_tag: '1A',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-12',
      property_id: 'demo-investor-3',
      title: 'Smoke detector test - Unit 2C',
      description: 'Monthly safety check.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      unit_tag: '2C',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-13',
      property_id: 'demo-investor-3',
      title: 'Smoke detector test - Unit 3B',
      description: 'Monthly safety check.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      unit_tag: '3B',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-14',
      property_id: 'demo-investor-3',
      title: 'Check parking lot lighting',
      description: 'Replace any burnt-out security lights.',
      priority: 'Medium',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 40,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      diy_cost: 40,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    {
      id: 'exec-today-15',
      property_id: 'demo-investor-3',
      title: 'Mailbox area cleanup',
      description: 'Clean and organize common mailbox area.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoDate(0), // TODAY
      current_fix_cost: 0,
      cascade_risk_score: 1,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    
    // ==========================================
    // SCHEDULED TASKS - FUTURE DATES (CALENDAR)
    // ==========================================
    
    // PROPERTY 1: MAPLE STREET DUPLEX - Scheduled
    {
      id: 'inv-task-1',
      property_id: 'demo-investor-1',
      title: 'Annual Safety Inspections - Maple Street',
      description: 'State law requires annual CO/smoke detector testing for rentals.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(5),
      current_fix_cost: 150,
      cascade_risk_score: 3,
      cascade_risk_reason: 'Non-compliance = $500-$2000 fines',
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      contractor_cost: 150,
      execution_method: 'Contractor'
    },
    {
      id: 'inv-task-2',
      property_id: 'demo-investor-1',
      title: 'Water Heater Replacement - Unit A',
      description: 'Unit A water heater is 11 years old. Proactive replacement prevents emergency scenario mid-winter.',
      priority: 'Medium',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(40),
      current_fix_cost: 1200,
      delayed_fix_cost: 1700,
      cascade_risk_score: 6,
      cascade_risk_reason: 'Emergency replacement costs 40% more + tenant satisfaction risk',
      system_type: 'Plumbing',
      source: 'PRESERVATION_RECOMMENDATION',
      unit_tag: 'A',
      contractor_cost: 1200,
      execution_method: 'Contractor'
    },
    {
      id: 'inv-task-3',
      property_id: 'demo-investor-1',
      title: 'Gutter Cleaning - Fall Service',
      description: 'Clean gutters before rainy season to prevent overflow and foundation damage.',
      priority: 'Medium',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(8),
      current_fix_cost: 150,
      cascade_risk_score: 5,
      system_type: 'Gutters',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      contractor_cost: 150,
      execution_method: 'Contractor'
    },
    {
      id: 'inv-task-4',
      property_id: 'demo-investor-1',
      title: 'Furnace Filter Change - Both Units',
      description: 'Replace HVAC filters for heating season.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(11),
      current_fix_cost: 40,
      cascade_risk_score: 2,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 40,
      execution_method: 'DIY'
    },
    {
      id: 'sched-1',
      property_id: 'demo-investor-1',
      title: 'HVAC filter replacement - Unit A',
      description: 'Replace filter for heating season.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(3),
      current_fix_cost: 45,
      cascade_risk_score: 2,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 45,
      execution_method: 'DIY'
    },
    {
      id: 'sched-2',
      property_id: 'demo-investor-1',
      title: 'HVAC filter replacement - Unit B',
      description: 'Replace filter for heating season.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(3),
      current_fix_cost: 45,
      cascade_risk_score: 2,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 45,
      execution_method: 'DIY'
    },
    {
      id: 'sched-3',
      property_id: 'demo-investor-1',
      title: 'Deck sealing - preventive maintenance',
      description: 'Seal deck to prevent water damage.',
      priority: 'Medium',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(55),
      current_fix_cost: 450,
      cascade_risk_score: 3,
      system_type: 'Exterior',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 450,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-4',
      property_id: 'demo-investor-1',
      title: 'Furnace tune-up - Unit A',
      description: 'Annual preventive maintenance.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(7),
      current_fix_cost: 185,
      cascade_risk_score: 2,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 185,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-5',
      property_id: 'demo-investor-1',
      title: 'Furnace tune-up - Unit B',
      description: 'Annual preventive maintenance.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(7),
      current_fix_cost: 185,
      cascade_risk_score: 2,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 185,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-6',
      property_id: 'demo-investor-2',
      title: 'HVAC tune-up before heating season',
      description: 'Annual preventive maintenance.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(2),
      current_fix_cost: 185,
      cascade_risk_score: 2,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 185,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-7',
      property_id: 'demo-investor-2',
      title: 'Gutter cleaning',
      description: 'Annual gutter cleaning before heavy rains.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(7),
      current_fix_cost: 125,
      cascade_risk_score: 4,
      system_type: 'Gutters',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 125,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-8',
      property_id: 'demo-investor-2',
      title: 'Chimney inspection',
      description: 'Annual chimney inspection before heating season.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(22),
      current_fix_cost: 175,
      cascade_risk_score: 2,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 175,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-9',
      property_id: 'demo-investor-2',
      title: 'Dryer vent cleaning',
      description: 'Prevent fire hazard.',
      priority: 'Medium',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(30),
      current_fix_cost: 95,
      cascade_risk_score: 6,
      system_type: 'Appliances',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 95,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-10',
      property_id: 'demo-investor-2',
      title: 'Water heater flush',
      description: 'Annual water heater maintenance.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(46),
      current_fix_cost: 120,
      cascade_risk_score: 2,
      system_type: 'Plumbing',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 120,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-11',
      property_id: 'demo-investor-3',
      title: 'Turnover Unit 4D - Deep Clean',
      description: 'Complete turnover within 7 days to minimize vacancy loss.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(2),
      current_fix_cost: 1850,
      cascade_risk_score: 6,
      cascade_risk_reason: 'Each day delayed = $30 lost revenue',
      system_type: 'General',
      source: 'MANUAL',
      unit_tag: '4D',
      contractor_cost: 1850,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-12',
      property_id: 'demo-investor-3',
      title: 'Refrigerator Repair - Unit 3B',
      description: 'Compressor making noise, likely needs replacement soon.',
      priority: 'Medium',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(18),
      current_fix_cost: 850,
      cascade_risk_score: 4,
      system_type: 'Appliances',
      source: 'INSPECTION',
      unit_tag: '3B',
      contractor_cost: 850,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-13',
      property_id: 'demo-investor-3',
      title: 'HVAC Filter Change - All Units',
      description: 'Quarterly filter changes for all 4 units.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(11),
      current_fix_cost: 60,
      cascade_risk_score: 2,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      diy_cost: 60,
      execution_method: 'DIY'
    },
    {
      id: 'sched-14',
      property_id: 'demo-investor-3',
      title: 'Landscaping Winter Prep',
      description: 'Trim trees, remove debris, prepare drainage for winter rains.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(10),
      current_fix_cost: 350,
      cascade_risk_score: 3,
      system_type: 'Landscaping',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 350,
      execution_method: 'Contractor'
    },
    {
      id: 'sched-15',
      property_id: 'demo-investor-3',
      title: 'Smoke Detector Testing - All Units',
      description: 'Test all smoke/CO detectors per code requirements.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: getDemoFutureDate(30),
      current_fix_cost: 0,
      cascade_risk_score: 3,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY'
    },
    
    // ==========================================
    // UNSCHEDULED TASKS - FOR SCHEDULE QUEUE
    // ==========================================
    
    // Property 1 - Unscheduled (NO scheduled_date = appears in queue)
    {
      id: 'unsched-1',
      property_id: 'demo-investor-1',
      title: 'Window caulking inspection - all windows',
      description: 'Check and repair window caulking to prevent drafts.',
      priority: 'Low',
      status: 'Identified',
      current_fix_cost: 120,
      cascade_risk_score: 2,
      system_type: 'Windows/Doors',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 120,
      execution_method: 'DIY'
    },
    {
      id: 'unsched-2',
      property_id: 'demo-investor-1',
      title: 'Pressure wash exterior - both units',
      description: 'Clean siding and prevent mold buildup.',
      priority: 'Low',
      status: 'Identified',
      current_fix_cost: 250,
      cascade_risk_score: 2,
      system_type: 'Exterior',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 250,
      execution_method: 'Contractor'
    },
    {
      id: 'unsched-3',
      property_id: 'demo-investor-1',
      title: 'Attic ventilation check',
      description: 'Ensure proper attic ventilation to prevent moisture.',
      priority: 'Medium',
      status: 'Identified',
      current_fix_cost: 85,
      cascade_risk_score: 4,
      system_type: 'Attic & Insulation',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 85,
      execution_method: 'DIY'
    },
    {
      id: 'unsched-4',
      property_id: 'demo-investor-1',
      title: 'Sump pump test - Unit B',
      description: 'Test sump pump operation before rainy season.',
      priority: 'Medium',
      status: 'Identified',
      current_fix_cost: 0,
      cascade_risk_score: 7,
      cascade_risk_reason: 'Failed pump = basement flooding',
      system_type: 'Plumbing',
      source: 'SEASONAL_CHECKLIST',
      unit_tag: 'B',
      diy_cost: 0,
      execution_method: 'DIY'
    },
    {
      id: 'unsched-5',
      property_id: 'demo-investor-1',
      title: 'Tree trimming - branches near roof',
      description: 'Trim overhanging branches to prevent roof damage.',
      priority: 'Medium',
      status: 'Identified',
      current_fix_cost: 450,
      cascade_risk_score: 5,
      system_type: 'Landscaping',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 450,
      execution_method: 'Contractor'
    },
    {
      id: 'unsched-6',
      property_id: 'demo-investor-1',
      title: 'Window Seal Repair - Unit B',
      description: 'Failed window seal causing fogging. Replace before winter.',
      priority: 'Low',
      status: 'Identified',
      current_fix_cost: 400,
      cascade_risk_score: 3,
      system_type: 'Windows/Doors',
      source: 'INSPECTION',
      unit_tag: 'B',
      contractor_cost: 400,
      execution_method: 'Contractor'
    },
    
    // Property 2 - Unscheduled
    {
      id: 'unsched-7',
      property_id: 'demo-investor-2',
      title: 'Garage door opener service',
      description: 'Lubricate and adjust garage door opener.',
      priority: 'Low',
      status: 'Identified',
      current_fix_cost: 120,
      cascade_risk_score: 2,
      system_type: 'Garage',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 120,
      execution_method: 'Contractor'
    },
    {
      id: 'unsched-8',
      property_id: 'demo-investor-2',
      title: 'Fence staining',
      description: 'Stain fence to protect from weather damage.',
      priority: 'Low',
      status: 'Identified',
      current_fix_cost: 850,
      cascade_risk_score: 2,
      system_type: 'Exterior',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 850,
      execution_method: 'Contractor'
    },
    {
      id: 'unsched-9',
      property_id: 'demo-investor-2',
      title: 'Crawl space moisture check',
      description: 'Inspect for water intrusion or dampness.',
      priority: 'Medium',
      status: 'Identified',
      current_fix_cost: 75,
      cascade_risk_score: 6,
      system_type: 'Foundation',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 75,
      execution_method: 'Contractor'
    },
    {
      id: 'unsched-10',
      property_id: 'demo-investor-2',
      title: 'Exterior outlet GFCI test',
      description: 'Test and replace GFCI outlets as needed.',
      priority: 'Medium',
      status: 'Identified',
      current_fix_cost: 0,
      cascade_risk_score: 3,
      system_type: 'Electrical',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY'
    },
    {
      id: 'unsched-11',
      property_id: 'demo-investor-2',
      title: 'Deck Inspection & Reseal',
      description: 'Inspect deck structure and reseal to prevent wood rot.',
      priority: 'Medium',
      status: 'Identified',
      current_fix_cost: 850,
      cascade_risk_score: 5,
      system_type: 'Exterior',
      source: 'SEASONAL_CHECKLIST',
      contractor_cost: 850,
      execution_method: 'Contractor'
    },
    
    // Property 3 - Unscheduled
    {
      id: 'unsched-12',
      property_id: 'demo-investor-3',
      title: 'Parking lot seal coating',
      description: 'Seal asphalt to prevent cracking.',
      priority: 'Low',
      status: 'Identified',
      current_fix_cost: 1800,
      cascade_risk_score: 3,
      system_type: 'Driveways',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      contractor_cost: 1800,
      execution_method: 'Contractor'
    },
    {
      id: 'unsched-13',
      property_id: 'demo-investor-3',
      title: 'Mailbox cluster repair',
      description: 'Repair damaged mailbox cluster.',
      priority: 'Low',
      status: 'Identified',
      current_fix_cost: 280,
      cascade_risk_score: 1,
      system_type: 'General',
      source: 'MANUAL',
      contractor_cost: 280,
      execution_method: 'Contractor'
    },
    {
      id: 'unsched-14',
      property_id: 'demo-investor-3',
      title: 'Fire extinguisher inspection - all units',
      description: 'Annual fire extinguisher inspection per code.',
      priority: 'High',
      status: 'Identified',
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      diy_cost: 0,
      execution_method: 'DIY'
    },
    {
      id: 'unsched-15',
      property_id: 'demo-investor-3',
      title: 'Exterior stairway handrail tightening',
      description: 'Tighten loose handrails for safety.',
      priority: 'Medium',
      status: 'Identified',
      current_fix_cost: 150,
      cascade_risk_score: 4,
      system_type: 'General',
      source: 'INSPECTION',
      contractor_cost: 150,
      execution_method: 'Contractor'
    },
    {
      id: 'unsched-16',
      property_id: 'demo-investor-3',
      title: 'Landscape bed mulch refresh',
      description: 'Add fresh mulch to landscape beds.',
      priority: 'Routine',
      status: 'Identified',
      current_fix_cost: 650,
      cascade_risk_score: 1,
      system_type: 'Landscaping',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      contractor_cost: 650,
      execution_method: 'Contractor'
    },
    {
      id: 'unsched-17',
      property_id: 'demo-investor-3',
      title: 'Cedar Court Roof Replacement (Plan for Spring)',
      description: 'Asphalt shingles are 22 years old. Minor leaks starting in Unit 2C. Replace before rainy season.',
      priority: 'High',
      status: 'Identified',
      current_fix_cost: 14500,
      delayed_fix_cost: 23000,
      cascade_risk_score: 9,
      cascade_risk_reason: 'Delaying could cause $8K-$15K in interior water damage across 4 units',
      system_type: 'Roof',
      source: 'PRESERVATION_RECOMMENDATION',
      scope: 'building_wide',
      contractor_cost: 14500,
      execution_method: 'Contractor'
    },
    
    // ==========================================
    // TASKS FOR TODAY (Nov 20, 2024) - FOR EXECUTE PAGE
    // ==========================================
    
    // PROPERTY 1: MAPLE STREET - TODAY
    {
      id: 'exec-today-1',
      property_id: 'demo-investor-1',
      title: 'Check thermostat settings - Both Units',
      description: 'Verify heating mode is set correctly for winter season.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 1,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-2',
      property_id: 'demo-investor-1',
      title: 'Test all smoke detectors - Unit A',
      description: 'Monthly smoke/CO detector testing.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-3',
      property_id: 'demo-investor-1',
      title: 'Test all smoke detectors - Unit B',
      description: 'Monthly smoke/CO detector testing.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-4',
      property_id: 'demo-investor-1',
      title: 'Inspect weather stripping - Unit A',
      description: 'Check door weather stripping before cold snap.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 1,
      system_type: 'Windows/Doors',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    {
      id: 'exec-today-5',
      property_id: 'demo-investor-1',
      title: 'Check for drafts - Unit B',
      description: 'Inspect windows and doors for cold air leaks.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 1,
      system_type: 'Windows/Doors',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    
    // PROPERTY 2: OAK RIDGE - TODAY
    {
      id: 'exec-today-6',
      property_id: 'demo-investor-2',
      title: 'Test all smoke/CO detectors',
      description: 'Monthly safety check.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    {
      id: 'exec-today-7',
      property_id: 'demo-investor-2',
      title: 'Inspect basement for moisture',
      description: 'Check for any water intrusion or dampness.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 3,
      system_type: 'Foundation',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    {
      id: 'exec-today-8',
      property_id: 'demo-investor-2',
      title: 'Check furnace operation',
      description: 'Verify furnace is running efficiently.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'HVAC',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-9',
      property_id: 'demo-investor-2',
      title: 'Exterior walkthrough - storm prep',
      description: 'Check for loose items before winter storms.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'Exterior',
      source: 'SEASONAL_CHECKLIST',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    
    // PROPERTY 3: CEDAR COURT - TODAY
    {
      id: 'exec-today-10',
      property_id: 'demo-investor-3',
      title: 'Common area inspection - Cedar Court',
      description: 'Check hallways, stairwells, exterior lighting.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    {
      id: 'exec-today-11',
      property_id: 'demo-investor-3',
      title: 'Smoke detector test - Unit 1A',
      description: 'Monthly safety check.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      unit_tag: '1A',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-12',
      property_id: 'demo-investor-3',
      title: 'Smoke detector test - Unit 2C',
      description: 'Monthly safety check.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      unit_tag: '2C',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-13',
      property_id: 'demo-investor-3',
      title: 'Smoke detector test - Unit 3B',
      description: 'Monthly safety check.',
      priority: 'High',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      unit_tag: '3B',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    },
    {
      id: 'exec-today-14',
      property_id: 'demo-investor-3',
      title: 'Check parking lot lighting',
      description: 'Replace any burnt-out security lights.',
      priority: 'Medium',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 40,
      cascade_risk_score: 2,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      diy_cost: 40,
      execution_method: 'DIY',
      estimated_hours: 0.5
    },
    {
      id: 'exec-today-15',
      property_id: 'demo-investor-3',
      title: 'Mailbox area cleanup',
      description: 'Clean and organize common mailbox area.',
      priority: 'Routine',
      status: 'Scheduled',
      scheduled_date: '2025-11-20',
      current_fix_cost: 0,
      cascade_risk_score: 1,
      system_type: 'General',
      source: 'SEASONAL_CHECKLIST',
      scope: 'building_wide',
      diy_cost: 0,
      execution_method: 'DIY',
      estimated_hours: 0.25
    }
  ],

  inspections: [
    // PROPERTY 1: MAPLE STREET DUPLEX - Inspections
    {
      id: 'insp-1',
      property_id: 'demo-investor-1',
      season: 'Fall',
      year: 2024,
      inspection_date: '2024-10-15',
      status: 'Completed',
      completion_percentage: 100,
      issues_found: 3
    },
    {
      id: 'insp-2',
      property_id: 'demo-investor-1',
      season: 'Spring',
      year: 2024,
      inspection_date: '2024-04-20',
      status: 'Completed',
      completion_percentage: 100,
      issues_found: 1
    },
    {
      id: 'insp-3',
      property_id: 'demo-investor-1',
      season: 'Winter',
      year: 2024,
      inspection_date: '2024-01-10',
      status: 'Completed',
      completion_percentage: 100,
      issues_found: 2
    },
    
    // PROPERTY 2: OAK RIDGE - Inspections
    {
      id: 'insp-4',
      property_id: 'demo-investor-2',
      season: 'Fall',
      year: 2024,
      inspection_date: '2024-09-28',
      status: 'Completed',
      completion_percentage: 100,
      issues_found: 0
    },
    {
      id: 'insp-5',
      property_id: 'demo-investor-2',
      season: 'Spring',
      year: 2024,
      inspection_date: '2024-04-15',
      status: 'Completed',
      completion_percentage: 100,
      issues_found: 1
    },
    {
      id: 'insp-6',
      property_id: 'demo-investor-2',
      season: 'Winter',
      year: 2024,
      inspection_date: '2024-01-08',
      status: 'Completed',
      completion_percentage: 100,
      issues_found: 0
    },
    
    // PROPERTY 3: CEDAR COURT 4-PLEX - Inspections
    {
      id: 'insp-7',
      property_id: 'demo-investor-3',
      season: 'Fall',
      year: 2024,
      inspection_date: '2024-11-01',
      status: 'Completed',
      completion_percentage: 100,
      issues_found: 5
    },
    {
      id: 'insp-8',
      property_id: 'demo-investor-3',
      season: 'Spring',
      year: 2024,
      inspection_date: '2024-04-25',
      status: 'Completed',
      completion_percentage: 100,
      issues_found: 4
    },
    {
      id: 'insp-9',
      property_id: 'demo-investor-3',
      season: 'Winter',
      year: 2024,
      inspection_date: '2024-01-15',
      status: 'Completed',
      completion_percentage: 100,
      issues_found: 3
    }
  ],

  maintenanceHistory: [
    // PROPERTY 1: MAPLE STREET DUPLEX - History
    {
      id: 'maint-1',
      property_id: 'demo-investor-1',
      title: 'Gutter cleaning (both units)',
      completion_date: '2024-10-20',
      actual_cost: 150,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 4200,
      system_type: 'Gutters'
    },
    {
      id: 'maint-2',
      property_id: 'demo-investor-1',
      title: 'HVAC tune-up - Unit A',
      completion_date: '2024-09-15',
      actual_cost: 185,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 1200,
      system_type: 'HVAC'
    },
    {
      id: 'maint-3',
      property_id: 'demo-investor-1',
      title: 'HVAC tune-up - Unit B',
      completion_date: '2024-09-15',
      actual_cost: 185,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 1200,
      system_type: 'HVAC'
    },
    {
      id: 'maint-4',
      property_id: 'demo-investor-1',
      title: 'Siding power wash',
      completion_date: '2024-08-05',
      actual_cost: 300,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 800,
      system_type: 'Exterior'
    },
    {
      id: 'maint-5',
      property_id: 'demo-investor-1',
      title: 'Garage door spring adjustment',
      completion_date: '2024-07-10',
      actual_cost: 125,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 600,
      system_type: 'Garage'
    },
    {
      id: 'maint-6',
      property_id: 'demo-investor-1',
      title: 'Unit A dishwasher repair',
      completion_date: '2024-06-12',
      actual_cost: 180,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 700,
      system_type: 'Appliances'
    },
    {
      id: 'maint-7',
      property_id: 'demo-investor-1',
      title: 'Landscape trimming',
      completion_date: '2024-05-20',
      actual_cost: 200,
      execution_type: 'Professional',
      status: 'Completed',
      system_type: 'Landscaping'
    },
    {
      id: 'maint-8',
      property_id: 'demo-investor-1',
      title: 'Spring HVAC service - both units',
      completion_date: '2024-04-10',
      actual_cost: 370,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 2400,
      system_type: 'HVAC'
    },
    
    // PROPERTY 2: OAK RIDGE - History
    {
      id: 'maint-9',
      property_id: 'demo-investor-2',
      title: 'HVAC annual service',
      completion_date: '2024-09-15',
      actual_cost: 185,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 1500,
      system_type: 'HVAC'
    },
    {
      id: 'maint-10',
      property_id: 'demo-investor-2',
      title: 'Gutter cleaning',
      completion_date: '2024-10-12',
      actual_cost: 125,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 3200,
      system_type: 'Gutters'
    },
    {
      id: 'maint-11',
      property_id: 'demo-investor-2',
      title: 'Roof inspection after windstorm',
      completion_date: '2024-10-05',
      actual_cost: 125,
      execution_type: 'Professional',
      status: 'Completed',
      system_type: 'Roof'
    },
    {
      id: 'maint-12',
      property_id: 'demo-investor-2',
      title: 'Water heater flush',
      completion_date: '2024-08-22',
      actual_cost: 140,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 1400,
      system_type: 'Plumbing'
    },
    {
      id: 'maint-13',
      property_id: 'demo-investor-2',
      title: 'Exterior paint touch-up',
      completion_date: '2024-07-15',
      actual_cost: 450,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 2000,
      system_type: 'Exterior'
    },
    {
      id: 'maint-14',
      property_id: 'demo-investor-2',
      title: 'Dryer vent cleaning',
      completion_date: '2024-06-01',
      actual_cost: 95,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 500,
      system_type: 'Appliances'
    },
    {
      id: 'maint-15',
      property_id: 'demo-investor-2',
      title: 'Spring landscaping cleanup',
      completion_date: '2024-04-18',
      actual_cost: 275,
      execution_type: 'Professional',
      status: 'Completed',
      system_type: 'Landscaping'
    },
    
    // PROPERTY 3: CEDAR COURT 4-PLEX - History
    {
      id: 'maint-16',
      property_id: 'demo-investor-3',
      title: 'Emergency plumbing repair - Unit 3B',
      completion_date: '2024-11-05',
      actual_cost: 385,
      execution_type: 'Professional',
      status: 'Completed',
      system_type: 'Plumbing'
    },
    {
      id: 'maint-17',
      property_id: 'demo-investor-3',
      title: 'Repaint Unit 1A after move-out',
      completion_date: '2024-08-12',
      actual_cost: 850,
      execution_type: 'Professional',
      status: 'Completed',
      system_type: 'General'
    },
    {
      id: 'maint-18',
      property_id: 'demo-investor-3',
      title: 'Gutter cleaning - all units',
      completion_date: '2024-10-15',
      actual_cost: 220,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 5500,
      system_type: 'Gutters'
    },
    {
      id: 'maint-19',
      property_id: 'demo-investor-3',
      title: 'Parking lot pothole repair',
      completion_date: '2024-09-20',
      actual_cost: 650,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 1800,
      system_type: 'Driveways'
    },
    {
      id: 'maint-20',
      property_id: 'demo-investor-3',
      title: 'Unit 2C toilet repair',
      completion_date: '2024-09-01',
      actual_cost: 175,
      execution_type: 'Professional',
      status: 'Completed',
      system_type: 'Plumbing'
    },
    {
      id: 'maint-21',
      property_id: 'demo-investor-3',
      title: 'Broken window replacement - Unit 1A',
      completion_date: '2024-07-22',
      actual_cost: 280,
      execution_type: 'Professional',
      status: 'Completed',
      system_type: 'Windows/Doors'
    },
    {
      id: 'maint-22',
      property_id: 'demo-investor-3',
      title: 'Unit 4D turnover - Spring',
      completion_date: '2024-05-15',
      actual_cost: 1650,
      execution_type: 'Professional',
      status: 'Completed',
      system_type: 'General'
    },
    {
      id: 'maint-23',
      property_id: 'demo-investor-3',
      title: 'Tree removal - storm damage',
      completion_date: '2024-03-18',
      actual_cost: 1200,
      execution_type: 'Professional',
      status: 'Completed',
      prevented_cost: 8000,
      system_type: 'Landscaping'
    },
    {
      id: 'maint-24',
      property_id: 'demo-investor-3',
      title: 'Electrical outlet repair - Unit 2C',
      completion_date: '2024-02-28',
      actual_cost: 145,
      execution_type: 'Professional',
      status: 'Completed',
      system_type: 'Electrical'
    }
  ],

  upgrades: [
    // PROPERTY 1: MAPLE STREET DUPLEX - Upgrades
    {
      id: 'inv-upgrade-1',
      property_id: 'demo-investor-1',
      title: 'Add In-Unit Washer/Dryer Hookups',
      category: 'Rental Income Boosters',
      description: 'Add W/D hookups to both units. Increases rent $75-100/unit per month.',
      status: 'Planned',
      investment_required: 5000,
      annual_savings: 2100,
      roi_timeline_months: 29,
      property_value_impact: 8000,
      priority_score: 9,
      planned_date: '2025-02-01'
    },
    {
      id: 'inv-upgrade-2',
      property_id: 'demo-investor-1',
      title: 'Smart Thermostat - Both Units',
      category: 'Energy Efficiency',
      description: 'Nest thermostats for both units. Remote control + energy savings.',
      status: 'Completed',
      investment_required: 550,
      actual_cost: 520,
      annual_savings: 280,
      roi_timeline_months: 22,
      property_value_impact: 1500,
      priority_score: 7,
      completion_date: '2024-08-15'
    },
    {
      id: 'inv-upgrade-3',
      property_id: 'demo-investor-1',
      title: 'LED Lighting Conversion',
      category: 'Energy Efficiency',
      description: 'Replace all bulbs with LED in both units.',
      status: 'Completed',
      investment_required: 280,
      actual_cost: 265,
      annual_savings: 240,
      roi_timeline_months: 13,
      property_value_impact: 500,
      priority_score: 6,
      completion_date: '2024-06-20'
    },
    
    // PROPERTY 2: OAK RIDGE - Upgrades
    {
      id: 'inv-upgrade-4',
      property_id: 'demo-investor-2',
      title: 'Smart Home Security Package',
      category: 'Rental Income Boosters',
      description: 'Smart doorbell, locks, thermostat. Premium tenant appeal.',
      status: 'In Progress',
      investment_required: 1050,
      annual_savings: 750,
      roi_timeline_months: 17,
      property_value_impact: 3000,
      priority_score: 8,
      progress_percentage: 65
    },
    {
      id: 'inv-upgrade-5',
      property_id: 'demo-investor-2',
      title: 'Attic Insulation Upgrade',
      category: 'Energy Efficiency',
      description: 'Increase R-value from R-30 to R-49. Reduces HVAC costs 15-20%.',
      status: 'Planned',
      investment_required: 2200,
      annual_savings: 450,
      roi_timeline_months: 59,
      property_value_impact: 3500,
      priority_score: 7,
      planned_date: '2025-03-01'
    },
    {
      id: 'inv-upgrade-6',
      property_id: 'demo-investor-2',
      title: 'Deck Rebuild',
      category: 'Curb Appeal',
      description: 'Replace aging deck with composite material. Low-maintenance + tenant appeal.',
      status: 'Identified',
      investment_required: 8500,
      annual_savings: 0,
      property_value_impact: 9000,
      priority_score: 5
    },
    
    // PROPERTY 3: CEDAR COURT 4-PLEX - Upgrades
    {
      id: 'inv-upgrade-7',
      property_id: 'demo-investor-3',
      title: 'Landscaping Refresh - Cedar Court',
      category: 'Curb Appeal',
      description: 'New bark, flower beds, pathway lighting. First impression matters for vacancy turnovers.',
      status: 'In Progress',
      progress_percentage: 35,
      investment_required: 2800,
      property_value_impact: 4500,
      priority_score: 5
    },
    {
      id: 'inv-upgrade-8',
      property_id: 'demo-investor-3',
      title: 'Energy Efficient Windows - All 4 Units',
      category: 'Energy Efficiency',
      description: 'Replace all single-pane windows with dual-pane low-E windows. Reduces heating costs 25-30% and increases property value.',
      status: 'Planned',
      investment_required: 9800,
      annual_savings: 840,
      roi_timeline_months: 140,
      property_value_impact: 6000,
      priority_score: 7,
      planned_date: '2025-05-01'
    },
    {
      id: 'inv-upgrade-9',
      property_id: 'demo-investor-3',
      title: 'Unit Refresh Package - 1A & 2C',
      category: 'Rental Income Boosters',
      description: 'New flooring, paint, fixtures for 2 units. Target $150/mo rent increase each.',
      status: 'Completed',
      investment_required: 8500,
      actual_cost: 8200,
      annual_savings: 3600,
      roi_timeline_months: 27,
      property_value_impact: 12000,
      priority_score: 9,
      completion_date: '2024-09-30'
    },
    {
      id: 'inv-upgrade-10',
      property_id: 'demo-investor-3',
      title: 'Parking Lot Striping & Lighting',
      category: 'Curb Appeal',
      description: 'Re-stripe parking lot and add LED security lighting.',
      status: 'Completed',
      investment_required: 1600,
      actual_cost: 1550,
      property_value_impact: 2500,
      priority_score: 4,
      completion_date: '2024-07-10'
    }
  ],

  preserveSchedules: [
    {
      id: 'preserve-inv-1',
      property_id: 'demo-investor-3',
      total_investment: 3800,
      total_replacement_costs_avoided: 21500,
      average_roi: 5.7,
      interventions: [
        {
          id: 'int-1',
          system_name: 'Roof System',
          intervention: 'Professional roof coating + targeted shingle repairs',
          description: '22-year-old asphalt shingles showing minor wear. Strategic coating extends life 5-7 years and seals minor leaks before they cascade.',
          investment_cost: 2200,
          replacement_cost_avoided: 14500,
          years_extended: 6,
          roi_multiplier: 6.6,
          frequency: 'One-time (then monitor)',
          status: 'Recommended',
          why_worth_it: '$2,200 now extends roof 6 years = delays $14,500 replacement. Prevents interior water damage across 4 units.',
          not_routine_because: 'This is NOT a cleaning. Strategic coating intervention extends capital asset life. Routine = gutter cleaning (ACT phase).'
        },
        {
          id: 'int-2',
          system_name: 'HVAC System',
          intervention: 'Add zoning controls + smart thermostats',
          description: 'Building HVAC is 39 years old but still functional. Adding zone controls reduces strain, extends life 3-5 years, cuts energy 20%.',
          investment_cost: 1200,
          replacement_cost_avoided: 6500,
          years_extended: 4,
          roi_multiplier: 5.4,
          frequency: 'One-time upgrade',
          status: 'Planned',
          why_worth_it: '$1,200 smart upgrade delays $18K HVAC replacement 4 years. Also saves $300/year on energy = extra ROI.',
          not_routine_because: 'This is capital improvement, not maintenance. Routine = filter changes (ACT phase).'
        }
      ]
    },
    {
      id: 'preserve-inv-2',
      property_id: 'demo-investor-1',
      total_investment: 1400,
      total_replacement_costs_avoided: 4800,
      average_roi: 3.4,
      interventions: [
        {
          id: 'int-3',
          system_name: 'Water Heater - Unit A',
          intervention: 'Install anode rod + flush sediment',
          description: '11-year-old water heater. Strategic anode replacement extends life 3-5 years, prevents emergency winter failure.',
          investment_cost: 350,
          replacement_cost_avoided: 1400,
          years_extended: 4,
          roi_multiplier: 4.0,
          frequency: 'Every 4-5 years',
          status: 'Recommended',
          why_worth_it: '$350 extends life 4 years. Avoids mid-winter emergency replacement at 2x cost + tenant disruption.',
          not_routine_because: 'Anode replacement is strategic preservation, not routine flush (that\'s ACT).'
        },
        {
          id: 'int-4',
          system_name: 'Water Heater - Unit B',
          intervention: 'Install anode rod + flush sediment',
          description: '11-year-old water heater. Strategic anode replacement extends life 3-5 years.',
          investment_cost: 350,
          replacement_cost_avoided: 1400,
          years_extended: 4,
          roi_multiplier: 4.0,
          frequency: 'Every 4-5 years',
          status: 'Recommended',
          why_worth_it: 'Same as Unit A. Do both at once for efficiency.',
          not_routine_because: 'Strategic preservation intervention.'
        },
        {
          id: 'int-5',
          system_name: 'Roof System',
          intervention: 'Preventive flashing repair + seal joints',
          description: 'Roof is 10 years old. Minor flashing gaps detected. Sealing now prevents major leaks and extends roof life 2-3 years.',
          investment_cost: 700,
          replacement_cost_avoided: 2000,
          years_extended: 3,
          roi_multiplier: 2.9,
          frequency: 'One-time',
          status: 'Optional',
          why_worth_it: '$700 to seal problem areas prevents $2K in emergency repairs + interior damage.',
          not_routine_because: 'Strategic sealing intervention, not routine gutter cleaning.'
        }
      ]
    }
  ],

  scaleData: {
    portfolioSummary: {
      totalProperties: 3,
      totalUnits: 7,
      totalValue: 785000,
      totalEquity: 412000,
      totalDebt: 373000,
      ltv: 47.5,
      avgHealthScore: 81,
      occupancyRate: 86,
      monthlyRevenue: 4850,
      monthlyExpenses: 2140,
      netCashFlow: 2710,
      annualizedROI: 18.2,
      cashOnCashReturn: 22.4
    },

    tenYearProjection: {
      currentEquity: 412000,
      projectedEquity2034: 892000,
      wealthGain: 480000,
      assumedAppreciation: 3.5,
      assumedRentGrowth: 2.8,
      projectedCashFlow2034: 5840,
      totalCashFlowDecade: 389000,
      totalWealth2034: 1281000
    },

    propertyComparison: [
      {
        property: 'Maple Street Duplex',
        healthScore: 84,
        equity: 142000,
        cashFlow: 1220,
        roi: 21.2,
        recommendation: 'Hold - Strong performer, minimal CapEx needed',
        nextMajorExpense: 'Roof replacement 2027 (~$8,500)'
      },
      {
        property: 'Oak Ridge Single Family',
        healthScore: 88,
        equity: 110000,
        cashFlow: 830,
        roi: 16.5,
        recommendation: 'Hold - Newer property, low maintenance, appreciating market',
        nextMajorExpense: 'HVAC replacement 2032 (~$6,200)'
      },
      {
        property: 'Cedar Court 4-Plex',
        healthScore: 72,
        equity: 115000,
        cashFlow: 1550,
        roi: 17.8,
        recommendation: 'Invest - Roof CapEx 2025 ($14.5K) will boost health score to 85+',
        nextMajorExpense: 'Roof replacement 2025 (~$14,500) - CRITICAL'
      }
    ],

    capExPlanning: {
      next12Months: 16500,
      next5Years: 42000,
      breakdown: [
        { item: 'Cedar Court Roof', year: 2025, cost: 14500 },
        { item: 'Maple Street Water Heaters', year: 2025, cost: 2400 },
        { item: 'Oak Ridge Deck Reseal', year: 2026, cost: 1200 },
        { item: 'Maple Street Roof', year: 2027, cost: 8500 },
        { item: 'Cedar Court HVAC', year: 2028, cost: 18000 }
      ]
    },

    acquisitionOpportunity: {
      message: 'Based on your cash flow ($2,710/mo) and equity ($412K), you could acquire a 4th property',
      potentialPurchasePrice: 350000,
      downPayment: 70000,
      projectedCashFlow: 950,
      newPortfolioROI: 19.1,
      recommendation: 'Consider HELOC on Maple Street ($142K equity) to fund down payment'
    }
  }
};