export const DEMO_PROPERTY_HOMEOWNER = {
  property: {
    id: 'demo-homeowner-001',
    address: '2847 Maple Grove Lane',
    street_address: '2847 Maple Grove Lane',
    city: 'Vancouver',
    state: 'WA',
    zip_code: '98661',
    property_type: 'Single-Family Home',
    year_built: 2015,
    square_footage: 2400,
    bedrooms: 4,
    bathrooms: 2.5,
    stories: 'Two-Story',
    foundation_type: 'Full Basement',
    garage_type: 'Attached 2-car',
    is_demo: true,
    demo_type: 'homeowner',
    baseline_completion: 100,
    health_score: 78,
    last_inspection_date: '2024-10-15',
    total_maintenance_spent: 3200,
    estimated_disasters_prevented: 7200,
    created_date: '2024-01-01T00:00:00Z'
  },
  
  systems: [
    {
      id: 'demo-h-sys-001',
      property_id: 'demo-homeowner-001',
      system_type: 'HVAC System',
      nickname: 'Main Heat Pump',
      brand_model: 'Lennox XC25 Heat Pump',
      installation_year: 2017,
      condition: 'Good',
      condition_notes: 'Serviced every 6 months. Last service: April 2024. Filter changed quarterly. Running at 95% efficiency.',
      last_service_date: '2024-04-10',
      next_service_date: '2024-10-15',
      estimated_lifespan_years: 15,
      replacement_cost_estimate: 8500,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-002',
      property_id: 'demo-homeowner-001',
      system_type: 'Water & Sewer/Septic',
      nickname: 'Water Heater',
      brand_model: 'Rheem ProTerra 50-Gal Hybrid',
      installation_year: 2016,
      condition: 'Fair',
      condition_notes: 'Showing signs of age. Minor sediment buildup detected during last flush. No leaks. Plan replacement within 12-18 months.',
      warning_signs_present: ['Sediment buildup', 'Age approaching end of lifespan'],
      last_service_date: '2024-03-15',
      next_service_date: '2025-03-15',
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 1800,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-003',
      property_id: 'demo-homeowner-001',
      system_type: 'Roof System',
      nickname: 'Main Roof',
      brand_model: 'CertainTeed Landmark AR Shingles',
      installation_year: 2015,
      condition: 'Good',
      condition_notes: '30-year architectural shingles. No missing/damaged shingles. Flashing intact. Gutters clean.',
      last_service_date: '2024-09-20',
      next_service_date: '2025-09-20',
      estimated_lifespan_years: 30,
      replacement_cost_estimate: 12000,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-004',
      property_id: 'demo-homeowner-001',
      system_type: 'Plumbing System',
      nickname: 'Main Plumbing',
      brand_model: 'Type L Copper Piping',
      installation_year: 2015,
      condition: 'Good',
      condition_notes: 'Copper supply lines, PVC drains. No visible leaks. Water pressure normal (60 PSI).',
      last_service_date: '2024-10-01',
      estimated_lifespan_years: 50,
      replacement_cost_estimate: 8000,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-005',
      property_id: 'demo-homeowner-001',
      system_type: 'Electrical System',
      nickname: 'Main Panel',
      brand_model: 'Square D 200A Main Panel',
      installation_year: 2015,
      condition: 'Excellent',
      condition_notes: '200-amp service. 32 circuit breakers. All labeled. GFCI outlets in kitchen, bathrooms, garage.',
      last_service_date: '2024-06-10',
      estimated_lifespan_years: 40,
      replacement_cost_estimate: 3500,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-006',
      property_id: 'demo-homeowner-001',
      system_type: 'Windows & Doors',
      nickname: 'All Windows',
      brand_model: 'Pella 250 Series Vinyl Double-Hung',
      installation_year: 2015,
      condition: 'Fair',
      condition_notes: 'Dual-pane vinyl windows. 3 windows have broken seals (foggy between panes). Consider replacement for those 3 within 1-2 years.',
      warning_signs_present: ['3 windows with failed seals', 'Reduced efficiency'],
      estimated_lifespan_years: 20,
      replacement_cost_estimate: 4500,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-007',
      property_id: 'demo-homeowner-001',
      system_type: 'Foundation & Structure',
      nickname: 'Foundation',
      brand_model: '8-inch Poured Concrete',
      installation_year: 2015,
      condition: 'Excellent',
      condition_notes: 'Poured concrete walls. No visible cracks. Proper drainage. Sump pump functioning.',
      last_service_date: '2024-09-01',
      estimated_lifespan_years: 100,
      replacement_cost_estimate: 50000,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-008',
      property_id: 'demo-homeowner-001',
      system_type: 'Basement/Crawlspace',
      nickname: 'Sump Pump',
      brand_model: 'Zoeller M53 Mighty-Mate',
      installation_year: 2015,
      condition: 'Good',
      condition_notes: '1/3 HP submersible pump with battery backup. Tested quarterly. At end of typical 10-year lifespan.',
      last_service_date: '2024-09-15',
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 800,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-009',
      property_id: 'demo-homeowner-001',
      system_type: 'Washing Machine',
      nickname: 'Washer Hoses',
      brand_model: 'Floodchek Braided Stainless Steel',
      installation_year: 2022,
      condition: 'Excellent',
      condition_notes: 'Braided stainless steel hoses (replaced rubber hoses). Auto-shutoff feature. No leaks.',
      last_service_date: '2024-06-01',
      estimated_lifespan_years: 5,
      replacement_cost_estimate: 50,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-010',
      property_id: 'demo-homeowner-001',
      system_type: 'Smoke Detector',
      nickname: 'All Smoke Detectors (6)',
      brand_model: 'First Alert Hardwired with Battery Backup',
      installation_year: 2015,
      condition: 'Urgent',
      condition_notes: 'Hardwired interconnected system. Units are 10 years old - REPLACE IMMEDIATELY per manufacturer guidelines.',
      warning_signs_present: ['Units at end of rated 10-year lifespan', 'Sensors may be degraded'],
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 300,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-011',
      property_id: 'demo-homeowner-001',
      system_type: 'Dishwasher',
      nickname: 'Kitchen Dishwasher',
      brand_model: 'Bosch SHPM65Z55N',
      installation_year: 2019,
      condition: 'Good',
      condition_notes: 'Stainless steel interior. Runs quietly. No leaks. Occasional error code (cleared by reset).',
      last_service_date: '2024-08-20',
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 800,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-012',
      property_id: 'demo-homeowner-001',
      system_type: 'Refrigerator',
      nickname: 'Kitchen Refrigerator',
      brand_model: 'Samsung RF28R7201SR French Door',
      installation_year: 2021,
      condition: 'Excellent',
      condition_notes: 'Counter-depth French door with ice maker. Cooling properly at optimal temps (37°F fridge, 0°F freezer).',
      last_service_date: '2024-07-01',
      estimated_lifespan_years: 13,
      replacement_cost_estimate: 2500,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-013',
      property_id: 'demo-homeowner-001',
      system_type: 'Range/Oven',
      nickname: 'Kitchen Range',
      brand_model: 'GE JGB735SPSS Gas Range',
      installation_year: 2015,
      condition: 'Good',
      condition_notes: '5-burner gas range. Oven calibrated correctly. All burners ignite properly.',
      last_service_date: '2024-06-15',
      estimated_lifespan_years: 15,
      replacement_cost_estimate: 1200,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-014',
      property_id: 'demo-homeowner-001',
      system_type: 'Microwave',
      nickname: 'Over-Range Microwave',
      brand_model: 'Whirlpool WMH53521HZ',
      installation_year: 2015,
      condition: 'Fair',
      condition_notes: 'Over-range microwave with vent. Heating inconsistent. Fan/light working. Consider replacement soon.',
      warning_signs_present: ['Magnetron may be weakening', 'Takes longer to heat'],
      estimated_lifespan_years: 9,
      replacement_cost_estimate: 400,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-015',
      property_id: 'demo-homeowner-001',
      system_type: 'Garage & Overhead Door',
      nickname: 'Garage Door Opener',
      brand_model: 'LiftMaster 8550W Elite Series',
      installation_year: 2020,
      condition: 'Good',
      condition_notes: 'Belt-drive opener with battery backup. WiFi enabled. Safety sensors functioning properly.',
      last_service_date: '2024-05-10',
      estimated_lifespan_years: 15,
      replacement_cost_estimate: 400,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    },
    {
      id: 'demo-h-sys-016',
      property_id: 'demo-homeowner-001',
      system_type: 'Exterior Siding & Envelope',
      nickname: 'Exterior Paint',
      brand_model: 'Sherwin-Williams Duration Exterior Acrylic',
      installation_year: 2018,
      condition: 'Fair',
      condition_notes: 'Beginning to fade and chalk. Minor peeling at eaves. Recommend repaint within 1-2 years to protect siding.',
      warning_signs_present: ['Paint oxidizing', 'Minor cracking at trim'],
      estimated_lifespan_years: 10,
      replacement_cost_estimate: 5500,
      photo_urls: [],
      created_date: '2024-01-15T00:00:00Z'
    }
  ],
  
  tasks: [
    {
      id: 'demo-h-task-001',
      property_id: 'demo-homeowner-001',
      title: 'Replace All Smoke Detectors',
      description: 'All 6 smoke detectors are 10 years old and must be replaced per manufacturer specifications. This is a critical life-safety issue.',
      system_type: 'General',
      priority: 'High',
      cascade_risk_score: 10,
      cascade_risk_reason: 'CRITICAL - Failed detection could result in injury/death in fire',
      current_fix_cost: 300,
      delayed_fix_cost: 300,
      urgency_timeline: 'Immediate - Already at end of rated lifespan',
      diy_cost: 250,
      diy_difficulty: 'Medium',
      diy_time_hours: 2.5,
      contractor_cost: 350,
      status: 'Identified',
      source: 'INSPECTION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-002',
      property_id: 'demo-homeowner-001',
      title: 'Budget for Water Heater Replacement (2025)',
      description: 'Water heater is 9 years old with sediment buildup. Plan replacement in next 12-18 months before failure occurs.',
      system_type: 'Plumbing',
      priority: 'High',
      cascade_risk_score: 7,
      cascade_risk_reason: 'Failure could flood garage and damage stored items',
      current_fix_cost: 1800,
      delayed_fix_cost: 3500,
      cost_impact_reason: 'Emergency replacement costs 2x more + water damage cleanup',
      urgency_timeline: '12-18 months before failure likely',
      contractor_cost: 1800,
      status: 'Identified',
      source: 'INSPECTION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-003',
      property_id: 'demo-homeowner-001',
      title: 'Replace 3 Windows with Failed Seals',
      description: 'Living room and master bedroom windows have broken seals causing fogging. Reducing energy efficiency.',
      system_type: 'Windows/Doors',
      priority: 'Medium',
      cascade_risk_score: 4,
      cascade_risk_reason: 'Reduced efficiency, higher heating/cooling costs',
      current_fix_cost: 1200,
      delayed_fix_cost: 1200,
      urgency_timeline: '12-24 months',
      contractor_cost: 1200,
      status: 'Identified',
      source: 'INSPECTION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-004',
      property_id: 'demo-homeowner-001',
      title: 'Proactive Sump Pump Replacement',
      description: 'Sump pump is 10 years old (end of typical lifespan). Replace before next rainy season to avoid basement flooding.',
      system_type: 'Plumbing',
      priority: 'High',
      cascade_risk_score: 8,
      cascade_risk_reason: 'Failure during heavy rain could flood basement',
      current_fix_cost: 800,
      delayed_fix_cost: 5000,
      cost_impact_reason: 'Basement flood cleanup and damaged items',
      urgency_timeline: 'Before rainy season (Nov-Mar)',
      diy_cost: 600,
      diy_difficulty: 'Medium',
      diy_time_hours: 3.5,
      contractor_cost: 1000,
      status: 'Identified',
      source: 'PRESERVATION_RECOMMENDATION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-005',
      property_id: 'demo-homeowner-001',
      title: 'Fall Gutter Cleaning',
      description: 'Annual gutter cleaning before rainy season. Prevents water damage to roof and foundation.',
      system_type: 'Gutters',
      priority: 'Medium',
      cascade_risk_score: 6,
      cascade_risk_reason: 'Overflow can damage roof edge and foundation',
      current_fix_cost: 200,
      delayed_fix_cost: 3000,
      cost_impact_reason: 'Water damage to fascia boards and foundation issues',
      urgency_timeline: 'Within 2 weeks',
      diy_cost: 0,
      diy_difficulty: 'Easy',
      diy_time_hours: 2,
      contractor_cost: 200,
      status: 'Identified',
      source: 'SEASONAL_CHECKLIST',
      seasonal: true,
      recommended_completion_window: 'Before Nov 15',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-006',
      property_id: 'demo-homeowner-001',
      title: 'Replace Microwave',
      description: 'Microwave heating inconsistently. Magnetron likely failing. Replace within 6-12 months.',
      system_type: 'Appliances',
      priority: 'Low',
      cascade_risk_score: 2,
      current_fix_cost: 400,
      delayed_fix_cost: 400,
      urgency_timeline: '6-12 months',
      contractor_cost: 400,
      status: 'Identified',
      source: 'INSPECTION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-007',
      property_id: 'demo-homeowner-001',
      title: 'Schedule Exterior Repainting',
      description: 'Exterior paint fading and chalking. Repaint in 2025 to protect siding from water damage.',
      system_type: 'Exterior',
      priority: 'Medium',
      cascade_risk_score: 5,
      cascade_risk_reason: 'Delayed painting could allow water damage to siding',
      current_fix_cost: 5500,
      delayed_fix_cost: 12000,
      cost_impact_reason: 'Water damage could require siding replacement',
      urgency_timeline: 'Next summer (dry weather)',
      contractor_cost: 5500,
      status: 'Identified',
      source: 'INSPECTION',
      created_date: '2024-10-15T00:00:00Z'
    },
    {
      id: 'demo-h-task-008',
      property_id: 'demo-homeowner-001',
      title: 'Fall HVAC Service',
      description: 'Bi-annual HVAC service before heating season. Ensures system runs efficiently through winter.',
      system_type: 'HVAC',
      priority: 'Medium',
      current_fix_cost: 150,
      delayed_fix_cost: 150,
      contractor_cost: 150,
      status: 'Scheduled',
      scheduled_date: '2024-10-28',
      source: 'SEASONAL_CHECKLIST',
      seasonal: true,
      contractor_name: 'ABC Heating & Cooling',
      created_date: '2024-10-15T00:00:00Z'
    }
  ],
  
  stats: {
    total_systems: 16,
    systems_good: 9,
    systems_flagged: 6,
    systems_urgent: 1,
    total_tasks: 8,
    tasks_urgent: 1,
    tasks_high: 3,
    tasks_medium: 3,
    tasks_low: 1,
    total_estimated_savings: 7200,
    health_score: 78
  }
};